/*
 Adform.RMB.js, version 2.1.75248

 Copyright Adform
 http://www.adform.com

 Date: 2014-08-07
*/
(function(a,h,c){function j(f,b){f.super_=b;n.prototype=b.prototype;f.prototype=new n;f.prototype.constructor=f}function n(){}function l(f,b){for(var m in b)b.hasOwnProperty(m)&&(f[m]=b[m]);return f}function i(f,b){return(b=b||c)&&b.getElementById&&b.getElementById(f)}function p(f,b){var m=!b?c:f.substr?i(f):f;return m?m.getElementsByTagName(b||f):[]}function w(f,b){return~(" "+f.className+" ").indexOf(" "+b+" ")}function e(f,b){w(f,b)&&(f.className=(" "+f.className+" ").replace(" "+b+" "," ").slice(1,
-1),e(f,b))}function b(f){var b=f.offsetTop,m=f.offsetLeft,e,a=k.curCSS,d="static"!=a(f,"position");b||(b=(parseFloat(a(f,"marginTop"))||0)+(d?parseFloat(a(f,"top"))||0:0));m||(m=(parseFloat(a(f,"marginLeft"))||0)+(d?parseFloat(a(f,"left"))||0:0));d&&f.getBoundingClientRect&&(e=k.offset(f,!0));!b&&e&&(b=e.top);!m&&e&&(m=e.left);return{top:b,left:m}}function d(f){var b={relativeX:f[s[0]],relativeY:f[s[1]]};if(null==f.pageX&&null!=f.clientX){var m=c.documentElement,e=c.body;b.pageX=f.clientX+(m&&m.scrollLeft||
e.scrollLeft||0);b.pageY=f.clientY+(m&&m.scrollTop||e.scrollTop||0)}else b.pageX=f.pageX,b.pageY=f.pageY;return b}function g(f,b){if(!(f=f.parentNode))return!1;var m=f.ownerDocument,e=m.body,a=k.curCSS,d;b&&(b+=1);if(h.$sf)return!0;if(k.isIE&&(8>m.documentMode||"BackCompat"==m.compatMode))return!1;for(;f&&f!=e;){if("hidden"==a(f,"overflow"))return!1;if("fixed"==a(f,"position"))break;else if(b&&(d=parseInt(a(f,"z-index"),10))&&d<b)return!1;f=f.parentNode}return!0}function q(){for(var b=0,m=[];b<L.length;b++)"complete"!=
L[b].document.readyState&&m.push(L[b]);if(!(L=m).length||3E4<(new Date).getTime()-ea){G=clearInterval(G);for(b=0;b<f.length;b++)f[b]();f=[];L=[]}}function C(f,b){var m=f.x+f.width,e=f.y+f.height,a=b.x+b.width,d=b.y+b.height,G=Math.max(f.x,b.x),g=Math.max(f.y,b.y),m=Math.min(m,a)-G,e=Math.min(e,d)-g;return 0<m&&0<e?{x:G,y:g,width:m,height:e}:{x:0,y:0,width:0,height:0}}function F(f,b,m,e){var a=function(f){e&&e.apply(f,arguments)},d=p(m,"head"),d=d&&d[0];if(!d)try{throw Error("Can't find head tag.");
}catch(G){a(G)}var g=b.src||b.href,u=g.replace(/[^\da-z_-]/gi,"_"),x=m.adformId||k.gid("doc_"),A=x+"|"+u,ea=Ga[A],u=k.byTag(m,f),i=0,c=u.length;m.adformId=m.adformId||x;if(ea)ea.loaded?a():ea.callbacks.push(a);else{for(;i<c;++i)if(u[i].src==g||u[i].href==g){a();return}Ga[A]=ea={doc:m,src:g,callbacks:[a]};var q=m.createElement(f),j;l(q,b);e&&(j=function(f){q.onload=q.onreadystatechange=q.onerror=null;f?Ga[A]=null:ea.loaded=1;var b=ea.callbacks;i=0;for(c=b.length;i<c;++i)b[i](f)},q.onload=function(){j()},
q.onreadystatechange=function(){"complete"==q.readyState&&j()},q.onerror=function(){try{throw Error("Failed to load script: "+g);}catch(f){j(f)}});setTimeout(function(){d.insertBefore(q,d.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var o=a.RMB,k=o.lib||(o.lib={});a.lib||(a.lib=k);k.inherit=j;k.define=function(f,b,m){m&&j(f,b);m(f,f.prototype)};k.gid=function(f){var b=+new Date;return(f||
"")+(b+b*~~(Math.random()*1E4)).toString(36)};k.byId=i;k.byTag=p;k.bind=function(f,b){return function(){return b.apply(f,arguments)}};k.extend=l;k.isMouseLeave=function(f,b){if(!f||f.type!="mouseout")return true;for(var m=f.relatedTarget||f.toElement,e,a=b.length;m;){for(e=0;e<a;e++)if(b[e]==m)return false;m=m.parentNode}return true};k.singleCall=function(f){function b(){d=false;var f=e,G=m,g=a;m=e=a=null;f&&f.apply(G,g)}var m,e,a,d;return function(G,g){m=G;e=g;a=B.call(arguments,2);if(g&&!d)d=setTimeout(b,
f);else if(!g&&d){clearTimeout(d);d=false}}};k.onload=function(b,e){try{do{if(b[m])break;b[m]=true;if(b.document.readyState!="complete"){L.push(b);if(!G){ea=(new Date).getTime();G=setInterval(q,200)}}}while(b!=b.parent&&(b=b.parent))}catch(a){}G?f.push(e):setTimeout(e,0)};k.overlap=C;k.overlapElem=function(f,b){var m=k.offset(f),e=k.offset(b);return C({x:m.left,y:m.top,width:f.offsetWidth,height:f.offsetHeight},{x:e.left,y:e.top,width:b.offsetWidth,height:b.offsetHeight})};k.hasClass=w;k.addClass=
function(f,b){if(!w(f,b))f.className=f.className+(" "+b)};k.removeClass=e;k.loadScript=function(f,b,m){F("script",{src:b,type:"text/javascript"},f,m)};k.loadCSS=function(f,b){F("link",{href:b,type:"text/css",rel:"stylesheet"},f)};k.navigator=h.navigator;k.isTMX=function(f){try{var b=f.document,m=b&&b.body;return m&&w(m,"tmx")}catch(e){}return false};k.isolate=function(f,b){var m=f.__adform_isolate;if(!m){var e=f.document,m=p(e,"head")[0],e=e.createElement("script");e.type="text/javascript";e.text=
'function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';m.insertBefore(e,m.firstChild);m.removeChild(e);m=f.__adform_isolate}m?m(b):(new Function("window","("+b+")(window)"))(f)};var B=Array.prototype.slice;k.addEvent=function(f,b,m){return f[Q]?f[Q](b,m,false):f[R]?f[R]("on"+b,m):false};k.removeEvent=function(f,b,m){return f[E]?f[E](b,m,false):f[I]?f[I]("on"+b,m):false};var Q="addEventListener",E="removeEventListener",R="attachEvent",I="detachEvent",t=/([A-Z])/g,S=/^-?\d+(?:px)?$/i,
D=/^-?\d/,a=c.defaultView;k.curCSS=a&&a.getComputedStyle?function(f,b){var m=f.ownerDocument.defaultView;if(m&&(m=m.getComputedStyle(f,null)))return m.getPropertyValue(b.replace(t,"-$1").toLowerCase())||f.style[b]}:c.documentElement.currentStyle&&function(f,b){var m,e,a,d=f.currentStyle&&f.currentStyle[b];if(!S.test(d)&&D.test(d)){m=(a=f.style).left;if(e=f.runtimeStyle&&f.runtimeStyle.left)f.runtimeStyle.left=f.currentStyle.left;a.left=b==="fontSize"?"1em":d||0;d=a.pixelLeft+"px";a.left=m;if(e)f.runtimeStyle.left=
e}return d===""?"auto":d};var U=function(){function f(){return f}var b=c.body,m=c.createElement("div"),e;e=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();m.innerHTML='<div style="'+e+'visibility:hidden"><div style="'+e+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+e+'"><div style="'+e+'position:fixed;top:20px;"></div></div><div style="'+e+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+
e+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';b.insertBefore(m=m.firstChild,b.firstChild);e=m.childNodes;f.dnab=e[0].firstChild.offsetTop!==5;f.sfp=e[1].firstChild.offsetTop===20;f.sbfonv=e[2].firstChild.offsetTop===-5;f.dabftac=p(m,"td").offsetTop===5;b.removeChild(m);b=m=e=null;return U=f},W=/^t(?:able|d|h)$/i;k.offsetFromWindow=function(f){var m,e,a,d;e=f&&f.ownerDocument;if(!e)return null;a=e.documentElement;if("getBoundingClientRect"in a){try{m=f.getBoundingClientRect();
d=a.getBoundingClientRect()}catch(g){}if(!m)return{top:0,left:0};if(d.left>0||d.top>0){m.top=m.top-d.top;m.left=m.left-d.left}return{top:m.top,left:m.left}}m=e.defaultView||e.parentWindow;d=e.body;if(f===e.body)return b(f);f=k.offset(f);e=m&&m.pageYOffset||a.scrollTop||d.scrollTop;a=m&&m.pageXOffset||a.scrollLeft||d.scrollLeft;f.top=f.top-e;f.left=f.left-a;return f};k.offset="getBoundingClientRect"in c.documentElement?function(f,m){var e,d=f&&f.ownerDocument;if(!d)return null;if(!m&&f===d.body)return b(f);
try{e=f.getBoundingClientRect()}catch(a){}if(!e)return{top:0,left:0};var g=d.body,d=d.documentElement;return{top:e.top+(d.scrollTop||g.scrollTop)-(d.clientTop||g.clientTop||0),left:e.left+(d.scrollLeft||g.scrollLeft)-(d.clientLeft||g.clientLeft||0)}}:function(f){var m=f&&f.ownerDocument;if(!m)return null;if(f===m.body)return b(f);var e,d=f.offsetParent,a=m.documentElement,g=m.body;e=(m=m.defaultView)?m.getComputedStyle(f,null):f.currentStyle;for(var G=f.offsetTop,u=f.offsetLeft,x=U();(f=f.parentNode)&&
f!==g&&f!==a;){if(x.sfp&&e.position==="fixed")break;e=m?m.getComputedStyle(f,null):f.currentStyle;G=G-f.scrollTop;u=u-f.scrollLeft;if(f===d){G=G+f.offsetTop;u=u+f.offsetLeft;if(x.dnab&&(!x.dabftac||!W.test(f.nodeName))){G=G+(parseFloat(e.borderTopWidth)||0);u=u+(parseFloat(e.borderLeftWidth)||0)}d=f.offsetParent}if(x.sbfonv&&e.overflow!=="visible"){G=G+(parseFloat(e.borderTopWidth)||0);u=u+(parseFloat(e.borderLeftWidth)||0)}}if(e.position==="relative"||e.position==="static"){G=G+g.offsetTop;u=u+g.offsetLeft}if(x.sfp&&
e.position==="fixed"){G=G+Math.max(a.scrollTop,g.scrollTop);u=u+Math.max(a.scrollLeft,g.scrollLeft)}return{top:G,left:u}};k.client=function(f){var b,m,e,d,f=f.ownerDocument||f;m=f.defaultView||f.parentWindow;e=f.documentElement;d=f.body;if(m.innerWidth){f=m.innerWidth;b=m.innerHeight}else if(e){f=e.clientWidth;b=e.clientHeight;if(!f||d.clientHeight!=d.offsetHeight){f=Math.min(f||123456789,d.clientWidth||123456789);b=Math.min(b||123456789,d.clientHeight||123456789)}}else{f=d.clientWidth;b=d.clientHeight}return{left:m&&
m.pageXOffset||e&&e.scrollLeft||d&&d.scrollLeft||0,top:m&&m.pageYOffset||e&&e.scrollTop||d&&d.scrollTop||0,width:f,height:b}};k.isArray=Array.isArray||function(f){return Object.prototype.toString.call(f)=="[object Array]"};var s=[["offsetX","offsetY"],["layerX","layerY"]];k.getMousePos=function(f){for(var b;b=s.shift();)if(typeof f[b[0]]!="undefined"){s=b;break}b||(s=["x","y"]);k.getMousePos=d;return d(f)};var M=c.createElement("div");k.html=function(f,b){var m=!b&&M||b.createElement("div");m.innerHTML=
f;return m.firstChild&&m.removeChild(m.firstChild)};var a=k.navigator,x=a.vendor,a=a.userAgent,N=/Apple Computer/i.test(x),o=/Google/i.test(x),O=k.isIPad=/iPad/i.test(a),H=k.isIPhone=/iPhone/i.test(a),J=k.isIOS=O||H,X=k.isTouch="ontouchstart"in c.documentElement||"ontouchstart"in h,O=k.isOrientation="orientation"in h,H=k.isAndroid=!J&&(/Android/i.test(a)||X&&!/series60|symbian|windows ce|blackberry/i.test(a));k.isAndroidApp=H&&!/^(?:Opera|Mozilla)/i.test(a);var u;k.isIOSF=J&&(u=/\sos\s(\d+)_\d+/i.exec(a))&&
(u=4<u[1]>>0);var z=k.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||X;u=k.isIE=/msie|Trident/i.test(a);X=k.isFF=/Firefox[\/.]+[^\s]/i.test(a);k.isMACOS=/Mac OS X/i.test(a);k.isWinPhone=u&&z&&/Phone/gi.test(a);var z=k.isOpera=/Opera/i.test(a),y=k.isOperaMobile=/Opera\s(?!Mini)/i.test(a),v=k.isOperaMini=/Opera\sMini/i.test(a),x=k.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(x),J=k.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(J?N:o),N=k.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&
N,o=k.isInternet=H&&!J&&O&&/Safari\/[\.\d]+$/i.test(a)&&o;k.isAfmaSDK=/afma-sdk/i.test(a);var A=u?"msie":X?"firefox":y?"operaMobile":v?"operaMini":z?"opera":x?"operaWebKit":J?"chrome":N?"safari":o?"internet":!1;k.browser=function(){return A};if(k.isIE&&("Microsoft Internet Explorer"==k.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a)))k.ieVersion=parseFloat(RegExp.$1);k.testPlace=k.isIE&&8>k.ieVersion?function(){return false}:g;k.isSafari&&(k.safariVersion=parseFloat(/Version.([\d.]+)/.exec(a)[1]));
var L=[],f=[],m="__adform_onload",G,ea,Ga={}})(Adform=window.Adform||{},window,document);
(function(a){function h(){var c=a.Data;if(c&&(delete a.Data,c.videoSources&&c.streamingVideo&&!(0>c.clicktags.indexOf("&detectBW=true")))){for(var j=c.videoSources,h=j[0].file.replace(/^[^:]+:\/\/[^\/]+|[^\/]+$/g,""),l={},i,p=0,w=j.length,e,b,d;p<w;p++)if(j[p]&&(e=j[p].file)&&0<=e.indexOf(h)&&(b=e.match(/([^\/]+?)(\d+)\.f[l4]v$/))){d=l[b[1]]||[];d.push(b[2]);if(!i||l[i].length<=d.length)i=b[1];l[b[1]]=d}i&&(l[i].sort(function(b,e){return b-e}),c.clicktags+="&streamBaseName="+encodeURIComponent(i)+
"&streamBitrates="+l[i].join(","))}}a.BWDetect=h;h()})(Adform=window.Adform||{},window,document);
(function(a){function h(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=h;var c=Array.prototype.slice,a=h.prototype;a.emit=function(a){var h=this._events,l=!1,i=arguments;if(h&&(h=h[a]))if("function"==typeof h){switch(i.length){case 1:h.call(this);break;case 2:h.call(this,i[1]);break;case 3:h.call(this,i[1],i[2]);break;case 4:h.call(this,i[1],i[2],i[3]);break;default:h.apply(this,c.call(i,1))}l=!0}else if(h.length){for(var i=c.call(i,1),h=h.slice(),l=0,p=h.length;l<p;l++)h[l].apply(this,i);l=!0}else delete this._events[a];
return l};a.on=function(a,c){this._events||(this._events={});this.emit("newListener",a,c);var h=this._events;h[a]?"function"==typeof h[a]?h[a]=[h[a],c]:h[a].push(c):h[a]=c;return this};a.once=function(a,c){var h=c._once;h?h._times++:(h=c._once=function(){this.off(a,h);1>--h._times&&delete c._once;return c.apply(this,arguments)},h._times=1);return this.on(a,h)};a.off=function(a,c){if(!this._events||!this._events[a])return this;var h=this._events,i=h[a];if(i==c)return delete h[a],this;c&&c._once&&this.off(c._once);
if("function"==typeof i)return this;if(2>i.length&&i[0]==c)return delete h[a],this;for(var p=0,w=i.length,e=[];p<w;p++)i[p]!=c&&e.push(i[p]);e.length!=w&&(e.length?h[a]=e:delete h[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var c=this._events;c[a]?"function"==typeof c[a]&&(c[a]=[c[a]]):c[a]=[];return c[a]}})(Adform=window.Adform||{});
(function(a,h){function c(){c.super_.call(this);this._previous={};this._attributes={};this._sets=[]}a.RMB=a.RMB||{};var j=a.RMB,n=j.lib;j.StateEmitter=c;n.inherit(c,j.EventEmitter);j=c.prototype;j.set=function(a,c){var h=this._sets,j=this._attributes;if("object"==typeof a)for(var e in a)a.hasOwnProperty(e)&&(j[e]=a[e],h.push(e));else j[a]=c,h.push(a);return this.commit()};j.get=function(a){var c=this._attributes;return a?c[a]:c};j.attr=function(a,c){return"object"==typeof a||1<arguments.length?this.set(a,
c):this.get(a)};j.previous=function(a){var c=this._previous;return a?c[a]:c};j.changes=function(a){var c=this._attributes,j=this._previous,w=this._sets;if(a)return c[a]!==j[a]?c[a]:h;for(var e={},b=0;a=w[b];b++)c[a]!==j[a]&&(e[a]=c[a]);return e};j.commit=function(){var a=this._sets;if(this._commit||!a.length)return this;this._commit=!0;for(var c=this._attributes,h=this._previous,j=!1,e=this._changes||(this._changes={}),b=0,d;d=a[b];b++)c[d]!==h[d]&&c[d]!==e[d]&&(e[d]=c[d],j=!0,this.emit("change:"+
d,c[d],h[d],d));if(j){e={};j=!1;for(d in c)c[d]!==h[d]&&(e[d]=c[d],j=!0);j&&this.emit("change",e)}this._commit=!1;a.splice(0,b);if(a.length)return this.commit();this._changes=null;for(d in c)c.hasOwnProperty(d)&&(h[d]=c[d]);return this};j.onchange=function(a,c){return c?this.on("change:"+a,c):this.on("change",a)}})(Adform=window.Adform||{});
(function(a){function h(a){i.push(this);this._doc=a;this._events={};this.dispatchHover=l.bind(this,c)}function c(){for(var a=h._hoverTarget,b=[],d=h._hoverChain,g=w+"hover-",c;a&&"undefined"!=(c=typeof a.className);)"string"==c&&0<=a.className.indexOf(g)&&b.unshift(a),a=a.parentNode;var i=Math.max(b.length,d.length),a=RegExp(g+"\\S+","g");c=[];for(i-=1;0<=i&&d[i]!=b[i];i--){if(d[i])for(var l=j(d[i].className,g,a),o=0;o<l.length;o++)l[o].call(d[i],"hoverout",d[i]);if(b[i]){l=j(b[i].className,g,a);
for(o=0;o<l.length;o++)c.push([l[o],b[i]])}}if(c.length)for(i=0;i<c.length;i++)c[i][0].call(c[i][1],"hoverin",c[i][1]);h._hoverChain=b}function j(a,b,d){a=a.match(d);d=[];if(a){a=("x|"+a.join("|")).split("|"+b).slice(1);for(b=0;b<a.length;b++)p[a[b]]&&d.push(p[a[b]])}return d}function n(a){for(var b=0;b<i.length;b++)if(i[b]._doc==a)return i[b]}a.RMB=a.RMB||{};var a=a.RMB,l=a.lib;a.DOMEvents=h;var i=[],p={},w="adform-domevents-";h.destroy=function(a){var b;if(a)(b=n(a))&&b.destroy();else for(;i.length;)i[0].destroy()};
h.on=function(a,b,d){var c=a.ownerDocument;(h.find(c)||new h(c)).on(a,b,d);return this};h.off=function(a,b,d){var c=h.find(a.ownerDocument);c&&c.off(a,b,d);return this};h.find=n;h.dispatchHover=c;h.dispatchClick=function(a,b){for(var d=w+"click-",c=[],h;a&&"undefined"!=(h=typeof a.className);)"string"==h&&0<=a.className.indexOf(d)&&c.unshift(a),a=a.parentNode;h=RegExp(d+"\\S+","g");for(var i=c.length-1;0<=i;i--)for(var l=j(c[i].className,d,h),o=0;o<l.length;o++)l[o].call(c[i],"click",c[i],b)};h._hoverChain=
[];h._hoverTarget=null;a=h.prototype;a.on=function(a,b,d){var c=d._adform_dom_key;c||(c=d._adform_dom_key=l.gid());c in p||(p[c]=d);d=w+b+"-"+c;0>a.className.indexOf(d)&&(a.className+=" "+d,this.setup(b))};a.off=function(a,b,d){if(d=d._adform_dom_key)a.className=a.className.replace(w+b+"-"+d,"")};a.destroy=function(){var a=this._events,b,d,c,q=this._doc;for(b in a)for(d in c=a[b],c)l.removeEvent(q,d,c[d]);for(a=i.length;0<a--;)if(i[a]==this){i.splice(a,1);break}a=h._hoverChain;a[0]&&a[0].ownerDocument==
q&&(h._hoverChain=[],h._hoverTarget=null);this._doc=this._events=null};a.setup=function(a){if(!this._events[a]){this._events[a]={};var b=this._doc,d=b.defaultView||b.parentWindow,c,i;"hover"==a?(b.addEventListener?(c=function(a){h._hoverTarget!=a.target&&(h._hoverTarget=a.target,h.dispatchHover())},i=function(a){h._hoverTarget!=a.relatedTarget&&(h._hoverTarget=a.relatedTarget,h.dispatchHover())}):(c=function(){d=b.defaultView||b.parentWindow;h._hoverTarget!=d.event.srcElement&&(h._hoverTarget=d.event.srcElement,
h.dispatchHover())},i=function(){d=b.defaultView||b.parentWindow;h._hoverTarget!=d.event.toElement&&(h._hoverTarget=d.event.toElement,h.dispatchHover())}),l.addEvent(b,"mouseover",this._events[a].mouseover=c),l.addEvent(b,"mouseout",this._events[a].mouseout=i),l.addEvent(b,"mousemove",this._events[a].mousemove=c),h._hoverChain=[]):"click"==a&&(c=b.addEventListener?function(a){h.dispatchClick(a.target,a)}:function(a){d=b.defaultView||b.parentWindow;a=d.event;h.dispatchClick(a.srcElement,a)},l.addEvent(b,
"mousedown",this._events[a].mousedown=c))}}})(Adform=window.Adform||{},window,document);
(function(a,h,c){function j(a,e){"string"!=typeof a&&(e=a,a="default");if(this instanceof j)this._id="adfrom-styleSheet-"+a,this._doc=e||c;else return new j(a,e)}a.RMB=a.RMB||{};a=a.RMB;a.StyleSheet=j;var n=a.lib,l,i,p,a=j.prototype;a.node=function(){var a=this._doc,c=this._id,b=n.byId(c,a);b||(b=a.createElement("style"),b.type="text/css",b.id=c,b._rules={},n.byTag(a,"head")[0].appendChild(b));if(!l&&(i=b.sheet?"sheet":"styleSheet",a=b[i]))p=a.insertRule?function(a,b,c,e){a.insertRule(b+" {"+c+"}",
e)}:function(a,b,c,e){a.addRule(b,c,e)},l=a&&a.cssRules?"cssRules":"rules";return b};a.set=function(a,c){var b=this.node(),d=b[i],g,h;try{g=b._rules,h=g[a]}catch(j){}var n=a.split(/\s*,\s*/),o,k;try{if(1<n.length)for(o=n.length-1;0<=o;--o)this.set(n[o],c);else if(h)h.style.cssText+=";"+c;else if(!d||!d[l])b.appendChild(this._doc.createTextNode(a+"{"+c+"}"));else if(c){k=d[l].length;try{p(d,a,c,k)}catch(B){setTimeout(function(){p(d,a,c,k)},0)}g&&(g[a]=d[l][k])}}catch(Q){}return this};a.destroy=function(){var a=
n.byId(this._id,this._doc);a&&a.parentNode.removeChild(a);this._doc=null}})(Adform=window.Adform||{},window,document);
(function(a,h){function c(){var f=t.bind;c.super_.call(this);this.cssQueue=[];this.id=t.gid(s);this.set({showing:!1,visible:!0}).onchange("visible",E).onchange("element",E).onchange("zIndex",n).onchange(Q);this._contents={};this._pos={};this.findElement=f(this,l);this.repositionPage=f(this,o);this.repositionFloated=f(this,B);this.repositionSticky=f(this,F)}function j(f){var a,b;if(a=this._hub)b=this._hubName,a.emit("element",this,b,f)}function n(f){this.style({zIndex:f})}function l(){this._findCalls||
(this._findCalls=(new Date).getTime()+c.fTimeout);var f=t.byId(this.id,this._doc),b=this.get("frame");if(f)this.handleHover=t.bind(this,i),this.handleClick=t.bind(this,p),D.on(b||f,"hover",this.handleHover),t.addEvent(f,"mousedown",this.handleClick),f.innerHTML="",this.set("element",f),this.css(""),this.style();else if(this._findCalls>(new Date).getTime())setTimeout(this.findElement,0);else throw f=this.content(),a.Log.pushMessage(["Adbox"],"Adbox element not found",{bn:f&&f.options.bn}),Error("Adbox element not found");
}function i(f){var a=this.hovered="hoverin"==f;this.emit("hover",a,this);this.emit(f,a,this)}function p(f){this.emit("click",f||this._win.event)}function w(f){var a=this._doc;var b=this.get(),c=b.element;if(c)for(var b=c.className.match(RegExp(s+b.postype+"(-\\w+)?","g")),d=0;d<b.length;d++){var u=b[d];t.hasClass(c,u)&&t.removeClass(c,u)}c=f.from;a=f.type||(!c?"static":c.window==c?"fixed":c===a?"page":"floated");d=f.position||"";b=L.exec(d);d=A.exec(d);b=b?b[0]:x;d=d?d[0]:X;u=this.get();u.vpos=d;
u.hpos=b;u.postype=a;u.frompos=c;this.resetPosition&&this.resetPosition();e.apply(this,[a,u,f])}function e(f,a,c){var e=this,g=e._win,i=e._doc,A=a.element;A&&(t.addClass(A,s+f+"-"+a.vpos),t.addClass(A,s+f+"-"+a.hpos),t.addClass(A,s+f));e.positionType=f;if("static"==f)this.onchange("x",q).onchange("y",q).onchange("showing",q),this.resetPosition=function(){e.off("change:x",q).off("change:y",q).off("change:showing",q);e.resetPosition=null};else if("fixed"==f){var j=i.documentElement,r=i.body,y=!1,H=
!1,v=function(){if(a.fixedBounding!==false){var f=j.clientWidth||r.clientWidth,b=j.clientHeight||r.clientHeight,c=a.element,d=c.offsetWidth-a.x,c=c.offsetHeight-a.y;if(H!=f<d){f=(H=f<d)?0:"";e.style({left:f,marginLeft:f,marginRight:f})}if(y!=b<c){f=(y=b<c)?0:"";e.style({top:f,marginTop:f,marginBottom:f})}}};this.onchange("showing",v);t.addEvent(g,"resize",v);this.onchange(C);this.onchange("fixedBounding",function(f){if(f===false){f="";e.style({left:f,marginLeft:f,marginRight:f,top:f,marginTop:f,marginBottom:f})}else v()});
W&&(this.iOSFixed=function(){var f={},a=j.scrollLeft||r.scrollLeft,b=j.scrollTop||r.scrollTop,m=j.clientWidth||r.clientWidth,c=j.clientHeight||r.clientHeight;if(L=="L")f.left=a+"px";if(L=="C")f.left=a+Math.round(m/2)+"px";if(L=="R")f.right=-a+"px";if(l=="T")f.top=b+"px";if(l=="M")f.top=b+Math.round(c/2)+"px";if(l=="B")f.bottom=-b+"px";e.style(f)},t.addEvent(g,"scroll",this.iOSFixed));this.resetPosition=function(){e.off("change:showing",v).off(C);v&&t.removeEvent(g,"resize",v);e.iOSFixed&&t.removeEvent(g,
"scroll",e.iOSFixed);e.css("margin:0;left:auto;top:auto;");e.resetPosition=null}}else if("sticky"==f)this.onchange(F),this.handleResize=t.bind(this,d),t.addEvent(g,"resize",this.handleResize),t.addEvent(g,"scroll",this.handleResize),t.addEvent(g,"load",this.handleResize),this.handleResize(),setTimeout(this.handleResize,50),this.resetPosition=function(){e.off(F);if(e.handleResize){t.removeEvent(g,"resize",e.handleResize);t.removeEvent(g,"scroll",e.handleResize);t.removeEvent(g,"load",e.handleResize)}};
else if("page"==f){this.onchange(o);this.resizeDelay=t.singleCall(100);this.handleResize=t.bind(this,b);t.addEvent(g,"resize",this.handleResize);t.addEvent(g,"scroll",this.handleResize);t.addEvent(g,"load",this.handleResize);this.handleResize();var J=setInterval(this.handleResize,100);setTimeout(function(){clearInterval(J)},3E3);this.resetPosition=function(){e.off(o);if(e.handleResize){t.removeEvent(g,"resize",e.handleResize);t.removeEvent(g,"scroll",e.handleResize);t.removeEvent(g,"load",e.handleResize)}clearInterval(J)}}else if("floated"==
f)this.onchange(B),c.container!=c.from?(this.resizeDelay=t.singleCall(10),this.handleResize=t.bind(this,k),t.addEvent(g,"resize",this.handleResize),this._fromInt=setInterval(this.handleResize,500),t.onload(h,this.handleResize),setTimeout(this.handleResize,50)):setTimeout(function(){B.call(e)},0),this.resetPosition=function(){e.handleResize&&t.removeEvent(g,"resize",e.handleResize);clearInterval(e._fromInt)};else if("mobile"==f){var l=a.vpos,L=a.hpos,R,n,I,p=g.innerWidth,M=g.innerHeight,D=p>=M,U=!1,
f=function(){e.pos.width=e.pos.height=0},w=function(){if(a.showing&&!U){R=A.getBoundingClientRect();p=g.innerWidth;M=g.innerHeight;if(D&&p<M||!D&&p>=M){D=p>=M;U=true;setTimeout(function(){U=false},500)}else{D=p>=M;var f=a.width,b=a.height,c=e._vp,d=e.pos||{},f=e._hp?p*parseFloat(f)/100:f,b=c?M*parseFloat(b)/100:b;n=(parseFloat(d.left)||0)-R.left;I=(parseFloat(d.top)||0)-R.top;var G,h;L==N?G=Math.round(n+(p-f)/2):L==x?G=Math.floor(n):L==O&&(G=Math.ceil(n+(p-f)));l==u?h=Math.round(I+(M-b)/2):l==X?h=
Math.floor(I):l==z&&(h=Math.ceil(I+(M-b)));e.setPosition(h,G,0,0,0,0,f,b)}}},Q=setInterval(w,100);t.addEvent(g,"resize",w);t.addEvent(g,"scroll",w);e.onchange("showing",w).onchange("width",f).onchange("height",f);w();this.resetPosition=function(){t.removeEvent(g,"resize",w);t.removeEvent(g,"scroll",w);e.resetPosition=null;clearInterval(Q)}}}function b(){this.repositionPage({showing:1})}function d(){this.repositionSticky({showing:1})}function g(f){var a=f.defaultView||f.parentWindow;a.self||(a=h);
var b=f.documentElement||f.body;this._doc=f;this._win=a;this.sheet=S("adbox",f);if(!a.__adform_adbox_init){var c=S("adbox-static",f);c.set("."+s+"hidden","visibility:hidden").set("."+s+"mobile","position:absolute").set("."+s+"static","position:relative").set("."+s+"static-L","margin:0 auto 0 0").set("."+s+"static-C","margin:0 auto").set("."+s+"static-R","margin:0 0 0 auto").set("."+s+"static-I","display:inline-block;*display:inline;zoom:1").set("."+s+"floated","position:absolute;display:block!important").set("."+
s+"page,."+s+"fixed,."+s+"sticky","position:fixed;display:block!important").set("."+s+"page-L,."+s+"fixed-L","left:0").set("."+s+"page-C,."+s+"fixed-C","left:50%").set("."+s+"page-R,."+s+"fixed-R","right:0").set("."+s+"page-T,."+s+"fixed-T","top:0").set("."+s+"page-M,."+s+"fixed-M","top:50%").set("."+s+"page-B,."+s+"fixed-B","bottom:0").set("."+s+"overlay","position:fixed;right:0;bottom:0;width:300%;height:300%").set("."+s+"overlay iframe","display:none;position:absolute;top:0;right:0;width:100%;height:100%").set("* html ."+
s+"page,* html ."+s+"fixed","position:absolute").set("* html ."+s+"fixed-L","left:expression(eval(__adform_adbox_fixedLeft(this)))").set("* html ."+s+"fixed-C","left:expression(eval(__adform_adbox_fixedCenter(this)))").set("* html ."+s+"fixed-R","left:expression(eval(__adform_adbox_fixedRight(this)))").set("* html ."+s+"fixed-T","top:expression(eval(__adform_adbox_fixedTop(this)))").set("* html ."+s+"fixed-M","top:expression(eval(__adform_adbox_fixedMiddle(this)))").set("* html ."+s+"fixed-B","top:expression(eval(__adform_adbox_fixedBottom(this)))").set("* html ."+
s+"overlay","position:absolute;top:expression(eval(__adform_adbox_fixedTop(this)));left:expression(eval(__adform_adbox_fixedLeft(this)));width:100%;height:100%");U&&"BackCompat"==f.compatMode&&c.set("."+s+"page","position:absolute");a.__adform_adbox_fixedLeft=function(){return b.scrollLeft};a.__adform_adbox_fixedCenter=function(){return b.scrollLeft+Math.round(b.clientWidth/2)};a.__adform_adbox_fixedRight=function(f){return b.scrollLeft+b.clientWidth-f.offsetWidth};a.__adform_adbox_fixedTop=function(){return b.scrollTop};
a.__adform_adbox_fixedMiddle=function(){return b.scrollTop+Math.round(b.clientHeight/2)};a.__adform_adbox_fixedBottom=function(f){return b.scrollTop+b.clientHeight-f.offsetHeight};a.__adform_adbox_init=0}a.__adform_adbox_init++}function q(){var f=this.get();f.showing&&this.style({left:f.x+"px",top:f.y+"px"})}function C(f){var a=this.get();if(a.showing&&(!f||"x"in f||"y"in f||"width"in f||"height"in f||"showing"in f)){var f=a.vpos,b=a.width,c=a.height,d="",e=a.y,g=a.x;a.hpos==N&&(this._hp?d+="left:"+
(50-parseFloat(b)/2)+"%;":g-=b/2);f==u&&(this._vp?d+="top:"+(50-parseFloat(c)/2)+"%;":e-=c/2);this.css(d+"margin:"+e+"px "+-g+"px "+-e+"px "+g+"px")}}function F(f){var a=this.get();if(a.showing&&(!f||"x"in f||"y"in f||"width"in f||"height"in f||"showing"in f||"stickyOffset"in f)){var b=this._win,c=this._doc,d=a.element,e=this.from(),g=t.offsetFromWindow(e),f=a.stickyOffset||0;!0===f&&(g.top=t.offset(e).top,f=g.top);var h=this._hp,x=this._vp,A=a.x,i=a.y,k=h?d.offsetWidth:a.width||0,j=x?d.offsetHeight:
a.height||0,d=g.left,q=g.top,g=e.offsetWidth,e=e.offsetHeight,o=b.innerWidth||c.body.clientWidth,v=b.innerHeight||c.body.clientHeight,l=a.vpos,s=a.hpos,b=s==M,c=s==N,L=s==O,s=s==H,R=l==J,n=l==u,I=l==z,l=l==y;h&&(k=o*parseFloat(a.width)/100,this.style({width:k+"px"}));x&&(j=v*parseFloat(a.height)/100,this.style({height:j+"px"}));a=i+q+(R?-j:n?(e-j)/2:I?e-j:l?e:0);this.setPosition(a>f?a:f,A+d+(b?-k:c?(g-k)/2:L?g-k:s?g:0),0,0)}}function o(f){var a=this.get();if(a.showing&&(!f||"x"in f||"y"in f||"width"in
f||"height"in f||"showing"in f)){var b=this._win,c=a.vpos,d=a.hpos,e=a.x,g=a.y,h=a.element,x=this._hp,f=x?h.offsetWidth:a.width,h=this._vp?h.offsetHeight:a.height,A=d==M,i=d==N,k=d==O,j=d==H,q=c==J,o=c==u,v=c==z,l=c==y;if(this._absolute||"absolute"==t.curCSS(a.element,"position"))this._absolute||(t.removeEvent(b,"resize",this.handleResize),t.removeEvent(b,"scroll",this.handleResize)),this._absolute=!0,g=Math.round(c==u?-(h/2):0)+g,a=Math.round(d==N?-(f/2):0)+e,this.setPosition(null,null,v?0:g,k?0:
a,v?-g:0,k?-a:0);else{var d=this._doc,b=d.documentElement,s=d.body;Math.max(b&&b.clientWidth||0,s&&s.clientWidth||0);var d=b&&b.clientHeight||s&&s.clientHeight,c=Math.max(b&&b.scrollWidth||0,s&&s.scrollWidth||0),L=Math.max(b&&b.scrollLeft||0,s&&s.scrollLeft||0),b=Math.max(b&&b.scrollTop||0,s&&s.scrollTop||0);x&&this.style({width:(f=Math.round(c*parseFloat(a.width)/100))+"px"});a=-L+(A?-f:i?(c-f)/2:k?c-f:j?c:0)+e;g=-b+(q?-h:o?(d-h)/2:v?d-h:l?d:0)+g;e=this._pp||(this._pp={t:0,l:0});(e.t>-h&&e.l>-f||
g>-h&&a>-f)&&this.setPosition(g,a,0,0);e.t=g;e.l=a}}}function k(){if(this.get().showing){var f=this.from();if(f){var a=t.offset(f);a.w=f.offsetWidth;a.h=f.offsetHeight;f=this._lastFromPos;if(!f||f.left!=a.left||f.top!=a.top||f.w!=a.w||f.h!=a.h)this._lastFromPos=a,B.call(this)}}}function B(f){if(!f||"x"in f||"y"in f||"width"in f||"height"in f||"showing"in f){var a=this.get();if(a.showing){var b=this.from();if(b){var c=a.vpos,f=a.hpos,d={},e=this._hp,g=this._vp;e&&(d.width=Math.round(b.offsetWidth*
parseFloat(a.width)/100)+"px");g&&(d.height=Math.round(b.offsetHeight*parseFloat(a.height)/100)+"px");(e||g)&&this.style(d);var h=a.element,d=a.x,x=a.y,e=e?h.offsetWidth:a.width,g=g?h.offsetHeight:a.height,h=t.offset(b),a=a.element.parentNode;"static"!=t.curCSS(a,"position")&&(a=t.offset(a),h.top-=a.top,h.left-=a.left);var a=b.offsetWidth,b=b.offsetHeight,A=f==N,i=f==O,k=f==H,j=c==u,q=c==z,o=c==y,a=h.left+(f==M?-e:A?a/2:i?a-e:k?a:0),h=h.top+(c==J?-g:j?b/2:q?b-g:o?b:0),c=Math.round(c==u?-(g/2):0)+
x,f=Math.round(f==N?-(e/2):0)+d;this.setPosition(h,a,c,f)}}else this.setPosition(-3E3,-3E3,0,0)}}function Q(a){if(("width"in a||"height"in a)&&"mobile"!=this.positionType){var b=this.get(),a=b.width,b=b.height,c=this._hp="string"==typeof a&&0<a.indexOf("%"),d=this._vp="string"==typeof b&&0<b.indexOf("%");this.style({width:"auto"===a?a:c?a:a+"px",height:"auto"===b?b:d?b:b+"px"})}}function E(){var a=this.get(),b=a.visible,c=this,d=a.element;if(d){var e=this._visibilityTimer;e&&(e=clearTimeout(e));var g=
function(){c._visibilityTimer=!1;var a=d.className,f=~a.indexOf(" adform-adbox-hidden");f&&b?d.className=a.replace(" adform-adbox-hidden",""):!f&&!b&&(d.className=a+" adform-adbox-hidden")};d.addEventListener?U?g():e=setTimeout(g,b?10:100):g();this._visibilityTimer=e}this.set("showing",b&&!!a.element)}function R(a){this.emit("content:"+(a?"show":"hide"),this.get("element"),this);this.emit(a?"show":"hide")}a.RMB=a.RMB||{};var I=a.RMB,t=I.lib,S=I.StyleSheet,D=I.DOMEvents,U=t.isIOS,W=U&&!t.isIOSF,s=
"adform-adbox-",M="K",x="L",N="C",O="R",H="E",J="Y",X="T",u="M",z="B",y="N",v=[M,x,N,O,H,"I"],A=RegExp([J,X,u,z,y].join("|")),L=RegExp(v.join("|"));I.AdBox=c;c.LEFT_OUT=M;c.LEFT=x;c.CENTER=N;c.RIGHT=O;c.RIGHT_OUT=H;c.TOP_OUT=J;c.TOP=X;c.MIDDLE=u;c.BOTTOM=z;c.BOTTOM_OUT=y;c.INLINE="I";c.CLASS="adform-adbox";c.PREFIX=s;c.hPosRegExp=L;c.vPosRegExp=A;c.fTimeout=1E4;t.inherit(c,I.StateEmitter);c.toCustom=function(a,b,c){var d=L.exec(c),c=A.exec(c),d=d?d[0]:x,c=c?c[0]:X,e=b.width,g=b.height,h=a.width,a=
a.height,i=d==N,k=d==O,j=d==H,q=c==u,o=c==z,v=c==y;return{x:(d==M?-e:i?(h-e)/2:k?h-e:j?h:0)+b.x,y:(c==J?-g:q?(a-g)/2:o?a-g:v?a:0)+b.y}};I=c.prototype;I.css=function(a,b){if(this.sheet){if(this.cssQueue){var c=this.cssQueue,d=0,e=c.length;for(this.cssQueue=null;d<e;d+=2)this.css(c[d],c[d+1])}this.sheet.set("#"+this.id+(b?" "+a:""),b||a)}else this.cssQueue.push(a,b);return this};I.content=function(a,b,c){!c&&"string"==typeof b&&(c=b,b=!1);c=c||"main";a&&(this._contents[c]=a,a.bind(this),b&&(a=a.data,
this.set({width:a.width,height:a.height})));return this._contents[c]};I.setPosition=function(a,b,c,d,e,g,h,u){if(this.get("element")){var a={top:a,left:b,marginTop:c,marginRight:g,marginBottom:e,marginLeft:d,width:h,height:u},b=this.pos||{},c=!1,d={},x;for(x in a)a[x]!=b[x]&&(c=!0,d[x]=a[x]+"px");c&&(this.pos=a,this.style(d))}};I.from=function(){var a=this.get("frompos");if("string"==typeof a&&(a=t.byId(a,this._doc))){if("OBJECT"==a.nodeName&&30>a.offsetHeight){var b=t.byTag(a,"embed")[0];b&&20<b.offsetHeight&&
(a=b)}this.set("frompos",a)}return!a||a.attr&&!(a=a.get("element"))?void 0:a};I.style=function(a){var b=this.get("element");b?(this._styles&&(t.extend(b.style,this._styles),this._styles=null),a&&t.extend(b.style,a)):this._styles=t.extend(this._styles||{},a);return this};I.reset=w;I.destroy=function(){var a=this.get("element"),b=this.get("frame");if(a){this.emit("content:destroy",a,this);this.clear();this._contents=null;var c=this._win,d=this._doc;D.off(b||a,"hover",this.handleHover);t.removeEvent(a,
"mousedown",this.handleClick);this.resetPosition&&this.resetPosition();var e,g;(e=this.handleResize)&&t.removeEvent(c,"resize",e);(g=this._fromInt)&&clearInterval(g);--c.__adform_adbox_init||(S("adbox-static",d).destroy(),this.sheet.destroy(),c.__adform_adbox_fixedLeft=c.__adform_adbox_fixedCenter=c.__adform_adbox_fixedRight=c.__adform_adbox_fixedTop=c.__adform_adbox_fixedMiddle=c.__adform_adbox_fixedBottom=null);this.sheet=null;this._changes={};this._previous={};this._attributes={};a.parentNode&&
a.parentNode.removeChild(a)}};I.draw=function(a,b){var c,d,e,b=b||{};if(c=this._hub)d=this._hubName,c.emit("draw",this,d,b);this.set("frame",b.frame);c=b.container;d=b.before;e=b.from;a=c&&c.ownerDocument||d&&d.ownerDocument||e&&(e.ownerDocument||e._doc||(e.defaultView||e.parentWindow||e).document)||a;g.call(this,a);w.call(this,b);c=b;d=c.from;e=c.container;var h=c.before,u=this.get(),x=u.postype,A=this._doc,x='<div id="'+this.id+'" class="adform-adbox '+(u.visible?"":s+"hidden ")+s+x+" "+s+x+"-"+
u.vpos+" "+s+x+"-"+u.hpos+'">AdBox</div>';if(!d&&!h&&!e)A.write(x);else{try{A.body||A.write("<html><body></body></html>")}catch(i){}if(A.body.insertAdjacentHTML&&t.isIE){var k="afterBegin";d?(e||(e=A.body),"end"==h&&(k="beforeEnd")):h&&(k="beforeBegin",e=h);try{e.insertAdjacentHTML(k,x)}catch(j){A.write(x)}}else d?(e||(e=A.body),h=null):h&&(e=h.parentNode),e.insertBefore(t.html(x,A),h||e.firstChild)}this.set({x:c.x||u.x||0,y:c.y||u.y||0});this.onchange("showing",R);this.findElement();return this};
I.pull=function(a,b){var c=this.get();if(a in c)b.call(this,c[a]);else this.once("change:"+a,b);return this};I.publish=function(a,b){this._hubName=a;this._hub=b;this.pull("element",j);return this}})(Adform=window.Adform||{},window,document);
(function(a){var h,c;function j(a){var b=l?h:i?c:{},d;for(d in a)a.hasOwnProperty(d)&&b[d]&&(w[b[d]]=a[d])}if(!a.IframeApiWrapper){var n=new a.RMB.EventEmitter,l,i,p,w;p={over:!1,pushdown:!1};h={width:"width",height:"height",left:"offsetLeft",right:"offsetRight",top:"offsetTop",bottom:"offsetBottom"};c={width:"width",height:"height",left:"l",right:"r",top:"t",bottom:"b",pushdown:"push"};w={};n.support=p;n.init=function(a){i=a.$sf&&a.$sf.ext;if(a.inDapMgrIf||a.inDapIF||a.inFIF)try{l=a.$WLXRmAd||a.parent.$WLXRmAd}catch(b){}n.msAPI=
l;n.sfAPI=i;n.hasAPI=!(!l&&!i);l?(p.over=!0,p.pushdown=!1):i&&(a=i.supports(),p.over="1"===a["exp-ovr"],p.pushdown="1"===a["exp-push"])};n.register=function(a){j(a);l?l.init(w):i&&i.register(a.width,a.height,function(a){n.emit(a)})};n.update=j;n.expand=function(a){if(a)n.once("expanded",a);l?(l.expand(),n.emit("expanded")):i&&i.expand(w)};n.collapse=function(a){if(a)n.once("collapsed",a);l?(l.collapse(),n.emit("collapsed")):i.collapse()};a.IframeApiWrapper=n}})(Adform=window.Adform||{});
(function(a,h,c){function j(a,b){for(var f in b)b.hasOwnProperty(f)&&("object"==typeof b[f]?("object"!=typeof a[f]&&(a[f]={}),j(a[f],b[f])):a[f]=b[f])}function n(a){var b=a.options,f=b.socializeURL;if(f){var f={linkBack:f,css:b.css,position:"BL"},b=b.type,c=b!=Q&&a.expFlash||a.flash,d=b!=Q&&a.expHtml||a.html,e=a.expImage||c==a.flash&&a.image,g=a.video;c&&(c.social=q.extend({width:(b==Q?a.expFlash:c).width},f));e&&(e.social=q.extend({width:e.width},f));d&&(d.social=q.extend({width:d.ewidth},f));g&&
(g.social=q.extend({width:g.width},f),g.social.position="TL"==g.closeButtonAlign?"TLV":"TL")}}function l(a,b){switch(a.type){case F:case Q:b.closeButtonAlign={BR:"TL",TR:"BL",BL:"TR",TL:"BR"}[a.expPosition]||b.closeButtonAlign;"TR"==b.closeButtonAlign&&b.adNotice&&(b.closeButtonAlign="TL");break;case o:b.closeButtonAlign="TL"==a.position?"BR":"BL";break;case k:b.closeButtonAlign=b.adNotice?"TL":"TR"}}function i(){var b=a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()}function p(){return{title:U,
linkText:M,text:W,link:s}}function w(a,b){return a&&~a.indexOf(y)&&a.match(v)[1]||b&&b[z]||0}function e(a){if("string"!=typeof a)return a||{};for(var c={},a=a.split("&"),f=0,d=a.length,e;f<d;f++)e=a[f].split("="),c[e.shift()]=b(e.join("="));return c}function b(a){if(!a)return a;a=decodeURIComponent(a);0<=a.indexOf("&")||!a.indexOf("http")?a=encodeURIComponent(a):0<=a.indexOf(";CREFURL=")&&(a=a.split(";CREFURL="),a=a.concat(a.pop().split(";C=")),a=a[0]+";CREFURL="+encodeURIComponent(a[1])+(a[2]?";C="+
a[2]:""));return a}a.RMB=a.RMB||{};var d=a.RMB,g=d.DataParser||(d.DataParser={}),q=d.lib,C=d.EventEmitter,F=g.EXPANDING="expanding",o=g.TEARBACK="tearback",k=g.FLOATING="floating",B=g.STANDARD="standard",Q=g.SINGLE_EXPANDING="singleExpanding",E=g.INTERSTITIAL="interstitial",R=g.SLIDER="slider",I=/compoundSeqNo=(\d+)/,t=/;obaId=([^;]+)/,S=/\.js(\?|$)/i,D=/\.swf(\?|$)/i,U="Adform.com",W="Would you like to know more about why you are seeing this ad?",s="http://site.adform.com/privacy/adchoices/",M="Read more";
g.getData=function(){var d=a.RMBData;a.BannerList&&a.BannerList.length&&(d=a.BannerList.shift());if(d){var g=d,f=q.extend({},N),u=q.extend({},N),j=q.extend({},O),z=q.extend({},O),v=q.extend({},H),y=q.extend({},J),s=q.extend({},J),M={},r=q.extend({},X),W;try{W=h.MESSENGER||-1<location.host.toLowerCase().indexOf("rad.msn.com")}catch(U){}r.messenger=W;r.iframeManager=a.ADF_STUB;r.iab=h.inDapMgrIf||h.inDapIF||h.inFIF;r.iframeAPI=a.IframeApiWrapper;r.iframeAPI.init(h);var fa=!g.flashvars;r.backCompat=
!fa;var Z=g.clicktags=e(g.clicktags),ca=Z.backupClickUrl,Bb=[0,"MC","TC","TL","TR","BL","BR","ML","MR","BC"],oa,da,ia;for(ia in g){var P=x[ia]||ia,K=g[ia],Ha;switch(P){case "bsrc":!v.poster&&(v.poster=K);case "src":var ta=w(K,Z);oa=K.match(D)?f:K.match(S)?y:j;oa.src=K;oa.assetId=ta;!v.assetId&&(v.assetId=ta);break;case "besrc":v.poster=K;case "esrc":ta=w(K,Z);oa=K.match(D)?u:K.match(S)?s:z;oa.src=K;(oa.assetId=ta)&&(v.assetId=ta);break;case "width":case "height":f[P]=j[P]=M[P]=y[P]=K>>0;!v[P]&&(v[P]=
K>>0);break;case "ewidth":case "eheight":P=P.slice(1);u[P]=z[P]=v[P]=s[P]=K>>0;break;case "wmode":W&&"window"==K&&(K="opaque");case "version":case "quality":f[P]=u[P]=y[P]=s[P]=K;break;case "flashvars":da=f[P]=u[P]=y[P]=s[P]=K;break;case "link":ca=fa?b(encodeURIComponent(K)):K;break;case "css":Ha=K.split("/assets/css/"),r.scriptsBase=a.scriptBase||Ha[0]+"/",K=r.scriptsBase+"assets/css/"+Ha[1];case "sources":r[P]=v[P]=K;break;case "ADFPoliteSrc":M.src=K;M.assetId=w(K,Z);break;case "showType":r[P]=
0==K?1:2==K?2:0;break;case "hideType":r[P]=1==K?0:1;break;case "floatPosition":r[P]=Bb[K];break;case "behavior":r[P]={"0":"default",1:"pushdown",2:"sidekick",3:"floating",takeOver:"takeover",4:"slider"}[K];break;case "zIndex":var bb=parseInt(K,10);r[P]=isNaN(bb)?r.zIndex:bb;break;default:r[P]=K}}var Db=r.bn=Z.bn,Cb=r.userParams=r.userParams||{},ja=i(),V=ja&&ja.banners&&ja.banners[r.xId];if(V){var ka=V.clickEvent;if(ka&&(ka=ka.match(I))&&(ka=ka[1]))V.compoundSeqNo=r.seqNo=da.seqNo=ka&&+ka;!1===V.stubFileExists&&
!r.iframeAPI.sfAPI&&(r.forceBackup=!0);V.cookieID&&(da.icid=V.cookieID);var cb=ja.getPropByBn&&ja.getPropByBn("animURL",Db);cb&&(Cb.animURL=cb);var db=ja.getRotSeed&&ja.getRotSeed().id;db&&(da.hash=db);var eb=V.rotseqno;eb&&(da.rotseqno=eb);var fb=V.smid;fb&&(da.smid=fb);var gb=V.timeDiff;gb&&(da.timeDiff=gb);if(V.isDSPTag&&h!=h.parent)try{h.parent.document.getElementById,h.inFIF=r.iab=!0}catch(Rb){a.ADFIframe=1}var hb=V.unloadScriptVersion;hb&&(r.unloadVersion="v"+hb);V.sendUnloadData&&(r.sendUnload=
!0)}"takeover"==r.behavior&&(r.autoShow=0.01,r.autoHide=8);W&&(r.showDelay=Math.max(r.showDelay,0.5),r.restartAnimation=1);r.iframeAPI.msAPI&&!r.showType&&(r.showType=1);da.wmode=f.wmode;var ib=h.ADFDomainCDN;ib&&(da.hvfdomain=ib);var ha=r.type;ha==F&&"slider"==r.behavior&&(ha=r.type=R);if(ha==k||ha==E)ca=Z.clickTAG;if(ca){if(fa)for(var jb,$=3;$--&&(2>(jb=ca.indexOf("://"))||8<jb);)try{ca=decodeURIComponent(ca)}catch(Sb){$=0}y.link=s.link=j.link=z.link=v.link=M.link=ca}ha==o&&(r.behavior=o);var Ia=
p(),Ja;if(a.ADFIframe)Ja=location.search;else{for(var Eb=RegExp("[?;]bn="+r.bn+"\\b"),kb=r.seqNo&&RegExp("[?;]compoundSeqNo="+r.seqNo+"\\b"),ua,Ka=q.byTag(c,"script"),La=Ka.length;La--;){var Ba=Ka[La].src;if(Ba&&0<Ba.indexOf("adfscript")&&Ba.match(Eb)&&(!kb||Ba.match(kb))){ua=Ka[La];break}}if(q.isIE){for(var va=ua,lb=c.body;va&&va!=lb;)va=va.parentNode;va==lb&&(r.$tag=ua)}Ja=ua&&ua.src}var mb=Ja,Ma=mb&&mb.match(t);Ma&&Ma[1]&&(r.obaId=Ma[1],r.adNotice=1,Ia.link="http://site.adform.com/privacy/adchoices/");
if(V&&V.adNotice||r.adNotice)y.adNotice=f.adNotice=j.adNotice=Ia,ha!=F&&(v.adNotice=Ia),r.adNotice=1;if(ha==k&&(r.restartAnimation=1,V)){V.floatFrom&&(r.position=V.floatPosition>>0,r.floatFrom=V.floatFrom);var nb=parseInt(V.showFloat,10);r.showFloat=isNaN(nb)||1<=nb?1:0}ha==Q&&(u.src=f.src,s.src=y.src,"sidekick"!=r.behavior&&(r.sideKickAnim=1),!r.sideKickAnim&&(da.useAsMask=!1));var la=y.flashvars,ob=h.ADFDynamicDomain;la.staticDomain=la.domain;h.ADFDomain&&ob&&(la.domain=encodeURIComponent(ob));
var Na={};for(ia in la){K=la[ia];try{K=decodeURIComponent(K)}catch(Tb){}Na[ia]=K}var ma=g.videoSources,Oa=[],pb=ma,Fb=decodeURIComponent(la.staticDomain),Gb=decodeURIComponent(la.hvfdomain),qb;for(qb in pb){var pa=pb[qb];pa&&pa.file&&!~pa.file.indexOf("://")&&(pa.file=("true"==pa.isStreaming+""&&Gb||Fb)+pa.file)}if(ma){var rb=ma,Pa,Qa,Ra,Ca,Da,ga,Sa,qa,Ta,Ua,sb,tb,ub;Pa=[];Qa=a.ENV&&a.ENV.akamaiHost;tb=/avc1\.(..)(..)(..)/;ub=/mp4a\.40\.(?:2|5)/;for(Ra=rb.length;Ra--;)if(Ca=rb[Ra])if(Da=Ca.codecs,
ga=Ca.file,Da&&ga&&(ga.indexOf(Qa)||!~ga.indexOf("/master.m3u8")))Ta=(qa=Da.match(tb))&&qa[1].toLowerCase(),Ua=qa&&parseInt(qa[3],16),qa="42"===Ta&&30>=Ua||"4d"===Ta&&31>=Ua,sb=Da.match(ub),qa&&sb&&(Sa=ga.indexOf("/Stream/"),~Sa&&(ga=ga.substr(Sa,ga.length-1),Pa.unshift({file:Qa+ga+"/master.m3u8",mime:"application/x-mpegURL",codecs:Ca.codecs})));for(var ma=Pa.concat(ma),$=0,vb,Hb=ma.length;$<Hb;$++)(vb=ma[$])&&Oa.push(vb);Oa.length&&(Na.videoSources=v.sources=Oa)}y.flashvars=s.flashvars=Na;var wa=
r.AdformBgImage&&r,wb=i(),xb=wb&&wb.banners,yb;for(yb in xb){var Va=xb[yb];if(Va.bn==r.bn&&Va.AdformBgImage){wa=Va;break}}if(wa){var Wa='url("'+wa.AdformBgImage+'")',zb={Color:"",Repeat:"",Scroll:"",HorizontalPosition:"center",VerticalPosition:"top"},Xa;for(Xa in zb)Wa+=" "+(wa["AdformBg"+Xa]||zb[Xa]);r.wallpaper={link:wa.AdformBgLink,background:Wa}}var ra=r.position,Ya=r.expPosition;switch(r.type){case B:var Za={left:"L",center:"C",right:"R"};r.position=Za[ra]||(r.backCompat?"I":"C");break;case E:r.fixed=
1;var xa=(r.y?"T":"M")+(r.x?"L":"C");r.position=xa;r.x>>=0;r.y>>=0;break;case k:var $a=r.floatFrom,Ib={1:"M",2:"T",3:"T",4:"T",5:"B",6:"B",7:"M",8:"M",9:"B"},Jb={1:"C",2:"C",3:"L",4:"R",5:"L",6:"R",7:"L",8:"R",9:"C"},Kb={1:"M",2:"Y",3:"Y",4:"Y",5:"N",6:"N",7:"M",8:"M",9:"N"},Lb={1:"C",2:"C",3:"K",4:"E",5:"K",6:"E",7:"K",8:"E",9:"C"},Mb=$a?Kb:Ib,Nb=$a?Lb:Jb;r.x>>=0;r.y>>=0;if(!$a&&(0>r.x&&(r.x=0),0>r.y))r.y=0;var Ob=Mb[ra]||"M",Pb=Nb[ra]||"C",xa=(r.y?"T":Ob)+(r.x?"L":Pb);r.position=xa;break;case F:case Q:Za=
{left:"L",center:"C",right:"R"};r.position=r.colPosition=Za[ra]||ra;r.expPosition={custom:"TL","left-up":"BR",takeOver:"BR",left:"TR","left-down":"TR",up:"BL","right-up":"BL",down:"TL",right:"TL","right-down":"TL"}[Ya]||Ya;"custom"!=Ya&&(r.expX=r.expY=0);break;case o:xa="2"==""+ra?"TR":"TL",r.position=r.colPosition=r.expPosition=xa}r.disturber=new C;var T={};T.flash=T.colFlash=f;T.expFlash=u;T.image=T.colImage=j;T.expImage=z;T.video=v;T.html=T.colHtml=y;T.expHtml=s;T.polite=M;T.options=r;T.events=
new C;var aa=T.options,ya={zIndex:aa.zIndex-1};aa.overlayOpacity&&(ya.opacity=(aa.overlayOpacity>>0)/100);aa.overlayColor&&(ya.background=aa.overlayColor);var ab={bn:aa.bn,closeOnClick:aa.overlayCloseOnClick||1,style:ya},Ea=(aa.iab?parent:h).ADFORM_OVERLAY||h.ADFORM_OVERLAY,ba;if(aa.type==k&&Ea){for(var Fa=0,Qb=Ea.length;Fa<Qb;Fa++)if(aa.bn==Ea[Fa].bn){ba=Ea[Fa];break}if(ba&&("undefined"!=typeof ba.callFrom&&(ab.callFrom=ba.callFrom),"undefined"!=typeof ba.closeOnClick&&(ab.closeOnClick=ba.closeOnClick),
ba.color&&(ya.background=ba.color),ba.opacity))ya.opacity=ba.opacity}if(ba||aa.overlayOpacity)T.overlay=ab;var Y={};for($ in T)if(T[$].src||T[$].sources)Y[$]=T[$];Y.options=r;Y.events=T.events;T.overlay&&(Y.overlay=T.overlay);"window"!=f.wmode&&n(Y);v.sources&&(v.loop="true"==""+Z.loopVideo,v.muted="true"!=""+Z.soundOn,v.autoplay="true"==""+Z.autoPlay,l(r,v));if(q.isSafari&&6.1<=q.safariVersion&&(Y.image||Y.html||Y.expImage||Y.expHtml))delete Y.flash,delete Y.colFlash,delete Y.expFlash;return Y}};
g.parseFlashvars=e;g.fixFlashvarsValue=b;g.applyHooks=function(a,b){var f=a.options,c=f.bn,d=i(),e=((f.iab?parent:h)._adform||[]).slice(0);f.iab&&e.push.apply(e,h._adform||[]);d&&d.getPropByBn&&(d=d.getPropByBn("multiPanel",c))&&e.push.apply(e,d);if(q.isArray(e)&&e.length){for(var f=b||["",c,"#"+f.seqNo,c+"#"+f.seqNo,f.xId],c={},g=f.length,x=e.length,d=0;d<g;d++)c[f[d]]={};for(var k=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,v,N,z,y,o,d=0;d<x;d++)if(v=e[d][0].match(k),N=c[v[1]||""]){z=e[d][1];
if(v[2]){v=v[2].split(".");for(o=y={};1<v.length;)y=y[v.shift()]={};y[v[0]]=z;z=o}if(v=z.on)for(var s in v){if("function"==typeof v[s])a.events.on(s,v[s])}else if(z.init)a.events.on("init",z.init);v={};for(y in z)u[y]&&(v[y]=z[y]);j(N,v)}e=c[f[0]];for(d=1;d<g;d++)j(e,c[f[d]]);for(d in u)if(d in e){v=u[d].split(".");for(o=y={};1<v.length;)y=y[v.shift()]={};y[v[0]]=e[d];j(a,o)}}y=(a.html||a.flash||a.image||a.video||{}).adNotice||p();if(e=a.options._adNotice){for(var O in e)e.hasOwnProperty(O)&&(y[O]=
e[O]);delete a.options._adNotice}(!a.flash||"window"!=a.flash.wmode)&&n(a);a.video&&l(a.options,a.video);return a};var x={ADFInitFlash:"src",ADFFlash:"src",ADFTearFlash:"esrc",tearWidth:"ewidth",tearHeight:"eheight",fVer:"version",ADFVer:"version",clicktags:"flashvars",ADFBuckup:"bsrc",bclickUrl:"link",backupClickURL:"link",ADFBuckupClickURL:"link",videoSources:"sources",bannerAlign:"position",expandsTo:"expPosition",adfxid:"xId",ADFid:"xId",expandDelay:"showDelay",expandTime:"showTime",collapseTime:"hideTime",
autoShowAfter:"autoShow",showTimeout:"autoShow",autoCloseAfter:"autoHide",closeTimeout:"autoHide",showOnRollOut:"showType",closeOnRollOut:"hideType",keepCollapsed:"keepCollapsed",politeTimeout:"loadDelay",expandedX:"expX",expandedY:"expY","":""},N={src:"",width:0,height:0,version:7,play:!0,menu:!1,loop:!0,quality:"autohigh",wmode:"opaque",bgcolor:null,allowScriptAccess:"always",allowFullScreen:!0,flashvars:{}},O={src:"",width:0,height:0,link:""},H={width:0,height:0,poster:"",css:null,closeButtonAlign:null,
loop:"false",muted:"true",autoplay:"false",link:null,assetId:0},J={src:"",width:0,height:0,flashvars:{}},X={position:"L",colPosition:"C",expPosition:"TL",x:0,y:0,expX:0,expY:0,xId:"1x",zIndex:1E5,fixed:0,restartAnimation:0,clickEvent:"",showDelay:0,showType:0,hideType:0,autoShow:0,autoHide:0,behavior:"default",frameRate:0,showTime:0,hideTime:0,loadDelay:0,type:"none",keepCollapsed:0,sideKickAnim:1,landingPageTarget:"_blank",showFloat:1},u={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",
x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",fixedBounding:"options.fixedBounding",panel:"panel"},z="ADFassetID",y=z+"=",v=RegExp(y+"(\\d*)")})(Adform=window.Adform||{},window,document);
(function(a,h){function c(a,b,c){for(var a=a.replace(/[\r\n]+/g,b),d={},a=a.split(b),e=a.length,g,h,b=0;b<e;b++){h=a[b].split(c);g=h.shift();var i=d;h=h.join(c);i[g]=!h?null:"true"===h||"false"===h?"true"===h:1*h==h?1*h:h}return d}function j(a){var b=a.options,c=a.panel.from,d;!{standard:1,expanding:1,singleExpanding:1}[b.type]||"floating"==b.behavior?g.AdConstructor.initialize(a):("number"==typeof c?b=n(a):"string"==typeof c?(b=q.byId(a.panel.from,(a.options.iab?h.parent:h).document))?(i(a,{container:b},
!0),b=void 0):b=!0:(i(a,{before:a.options.iab&&h.frameElement},!0),b=void 0),d=b);d?(o.push(a),k||(k=setTimeout(l,100))):o.length&&j(o.shift())}function n(a){var c=B[a.options.bn+"#"+a.panel.from];if(!c||!c.box)return!0;var d=a.panel,e=b(d.position,!0),g=c.settings,h=g.image||g.html||g.video||g.flash,g=(g=g.panel)&&g.space,k;if(g&&h&&"C"!=e&&(k=g.width>>0))k=0.5*(k-h.width),d.x=(d.x||0)+("L"==e?-1:1)*k;c.box.pull("element",function(){i(a,{from:c.box})})}function l(){k=0;o.length&&j(o.shift())}function i(a,
c,d){function e(g){var h=v?"stickyBox":"box";y=H[h]=(new F).publish("panel-"+h,a.events);C&&y.set("zIndex",l.zIndex=C);y.set({width:f,height:J?m:"auto",x:!v&&x.x||0,y:!v&&x.y||0,visible:!x.hidden}).set(n?{stickyOffset:x.sticky}:{}).pull("element",i).draw(O,{type:n&&"sticky",position:v?"":b(x.position,d),container:u,before:z,from:g||c.from})}function i(b){b.innerHTML="<span></span>";l.iab=!1;l.window=N;l.$tag=b.firstChild;b={item:H,settings:a,content:o};l.panel=b.exports={set:q.bind(b,p),get:q.bind(b,
w)};b.constructor=A=g.AdConstructor.initialize(a);A._panel_show=A.show;A._panel_hide=A.hide;A.show=k;A.hide=j}function k(){var a=c.from;a&&a.pull&&!a.get("visible")?setTimeout(k,100):(v&&v.set("visible",!0),y.set("visible",!0),A._panel_show())}function j(){A._panel_hide();y.set("visible",!1);v&&v.set("visible",!1)}var o=a.image||a.html||a.flash,l=a.options,x=a.panel,N=l.iab?h.parent:h,O=N.document,H=B[l.bn+"#"+l.seqNo],J=!!c.from,n="sticky"in x&&!1!==x.sticky,u=c.container,z=c.before,y,v,A,C="z"in
x?x.z:n||J?1E4:null,f=o.width,m=o.height;l.hidden?x.hidden=l.hidden:x.hidden&&(l.hidden=x.hidden);n&&!J?(u=z=null,(v=H.box=new F).publish("panel-box",a.events).set({width:f,height:m,visible:!x.hidden,x:x.x||0,y:x.y||0}).pull("element",e).draw(O,{position:b(x.position,d),before:c.before,container:c.container})):e()}function p(a,b){var c=this.item,d=c.box,c=c.stickyBox,a=E[a]||a;if("string"!==typeof a)for(b in a)p.call(this,b,a[b]);else"zIndex"==a?((c||d).set(a,b),this.constructor.setZIndex(b)):c&&
"stickyOffset"==a?c.set(a,b):d.set(a,b);c&&c.repositionSticky()}function w(a){var b=this.item,c=b.box,a=E[a]||a;if("width"==a||"height"==a)a=this.content[a];else{if("zIndex"==a||"stickyOffset"==a)c=b.stickyBox||c;a=c.get(a)}return a}function e(a,b){var c=b.options,d=b.panel,e={options:{iab:c.iab},events:b.events};C.applyHooks(e,["#"+a,c.bn+"#"+a]);e.panel&&(d?q.extend(d,e.panel):b.panel=e.panel)}function b(a,b){var a=(a||"").toLowerCase(),c,d={r:"E",ri:"R",l:"K",li:"L"}[(c=a.match(/[rl]i?/))&&c[0]]||
"C",e={t:"Y",ti:"T",b:"N",bi:"B"}[(c=a.match(/[tb]i?/))&&c[0]]||"M";return b?{E:"R",K:"L"}[d]||d:d+e}function d(){}if(!a._panels){a._panels=!0;var g=a.RMB,q=g.lib,C=g.DataParser,F=g.AdBox,o=[],k,B={},Q={},E={z:"zIndex",sticky:"stickyOffset"};(_adform=h._adform||[]).push(["on.setup",function(b){var g=a.ADFUtilInstance,i=b.options,k=i.bn;if(g&&g.getPropByBn){var o=b.panel,l=b.events,n=i.seqNo,s=1==n,p;p=Q[k];if(!p)for(var x=q.byTag("script"),N=x.length,O,H;0<N--;)if(O=x[N],(H=O.getAttribute("data-panels"))&&
O.src&&~O.src.indexOf("?bn="+k)){var x=c(H,";","="),N={length:0},J=H=O=void 0,X={w:"width",h:"height",pos:"position",p:"position",f:"from",s:"sticky"},u=void 0;for(u in x)if(u){O=x[u]?c(x[u],",",":"):{};H={};for(var z in O)z&&(J=X[z]||z,H[J]="hidden"==J||null===O[z]||O[z]);N["#"+u]=H;N.length++}H=N;H.length&&(p=Q[k]=H);break}if(p&&(s&&!g.getPropByBn("syncMembersCount",k)&&g.addBannerAttribute(i.xId,"syncMembersCount",p.length),p=p["#"+n]))o=b.panel=q.extend(o||{},p);o&&(i.iab&&(h.frameElement.style.display=
"none"),B[k+"#"+n]={settings:b},s&&(o.id=o.id||"top"),o.id&&(l.clear("setup"),e(o.id,b),l.emit("setup",b)),b.preventInitialization=!0,j(b));if(s&&g.getPropByBn("singleTag",k)){g=a.ADFUtilInstance;b=b.options;i=g.getPropByBn("syncMembersCount",b.bn);k={options:{iab:b.iab,bn:b.bn},events:{on:d}};for(o=1;o++<(i||10);){if(!i){e(o,k);if(!k.panel)break;delete k.panel}g.copyBanner(b.xId,{compoundSeqNo:o,compoundImpr:0})}}}}])}})(Adform=window.Adform||{},window,document);
(function(a){function h(a,h,n){this._dur=n;this._int=h||25;this._fn=a;this._pos=0;var l=this;this.frame=function(a){l._frame(a)}}a.RMB=a.RMB||{};a.RMB.Tween=h;a=h.prototype;a.duration=function(a){this._dur=a;return this};a.forward=function(a){this.start(a)};a.backward=function(a){this.start(a,!0)};a.frame=function(a){a=!0===a?0:this._dur?(new Date-this._time)/this._dur:1;1<=a&&(a=1,this.stop());this._fn(this._back?1-a:a,this._back);this._pos=a};a._frame=a.frame;a.start=function(a,h){this.stop();"undefined"!=
typeof a?this._pos=a:a=this._pos;this._back!=h&&(a=1-a);this._back=!!h;this._time=new Date-this._dur*a;this._timer=setInterval(this.frame,this._int);this.frame(!a)};a.stop=function(){clearInterval(this._timer)}})(Adform=window.Adform||{});
(function(a){function h(b){if(!C)if(C=a.ADFEventsInstance){if(!C.getItem)return C=null;C.on("destroy",i);C.subscribe(l);l()}else b&&!q&&(q=1,e.AdConstructor.require(["engagement/EngagementTracker"],function(){}));return C}function c(a){var b=h();return b&&b.getItem(a)}function j(a){if(this instanceof j)throw Error('This function cannot be used with operator "new".');return g[a]||(g[a]=new p(a))}function n(){}function l(){for(var a in g)g[a].refresh()}function i(){for(var a in g)g[a].emit("destroy")}
function p(a){this.xId=a;this._queue=[];this._attributes={};this.set("visible",!1);this.set("loaded",!1);this.set("percent",0);this.set("clicksCount",0);this.refresh();this._changes=null;if(!h())this.once("newListener",w)}function w(){h(!0)}a.RMB=a.RMB||{};var e=a.RMB;if(!e.EngagementAPI){e.EngagementAPI=j;var b=e.lib,d=e.EventEmitter,g={},q,C,F;h()||(F=a._etCallback,a._etCallback=function(){h();(a._etCallback=F)&&F()});j.version=n;j.load=function(){h(true)};b.inherit(p,d);b=p.prototype;b.set=function(a,
b){var d=c(this.xId),e=this.get(a),g=this._changes;if(d)d.attr(a,b);else{this._attributes[a]=b;this._queue.push([a,b])}if(e!==b){if(!g)g=this._changes={};g[a]=b;this.emit("change:"+a,b,e)}return this};b.get=function(a){if(this["get_"+a])return this["get_"+a]();var b=c(this.xId);return b?b.attr(a):this._attributes[a]};b.get_visibleTime=function(){var a=c(this.xId);return a&&a.visibility.time};b.refresh=function(){var a;a=c(this.xId);var b=0,d=this._queue,e=d.length;if(a){if(e){for(;b<e;b++)a.attr(d[b][0],
d[b][1]);d.length=0}this.set("visible",a.visibility.active);this.set("percent",a.data.currentVisibleArea);this.set("clicksCount",a.clicks.length);if(a=this._changes){this._changes=null;this.emit("change",a)}}return this}}})(Adform=window.Adform||{},window,document);
(function(a,h,c){function j(d){var c=this.options=d.options;this.settings=d;c.BANNER_TYPE=this.BANNER_TYPE;var g=h;c.iab?(g=parent,c.iframe=h.frameElement):c.iframeManager?(g=parent.parent,c.iframe=l(g,parent)):c.window&&(g=c.window);this.win=g;B.isolate(g,w);a.adRegister=g.Adform.adRegister;p.call(this);(this._wallpaper=c.wallpaper&&c.wallpaper.background&&!B.isTMX(g))&&this.setupWallpaper();var k=d.events;this.on=function(){k.on.apply(k,arguments);return this};this.off=function(){k.off.apply(k,
arguments);return this};this.once=function(){k.once.apply(k,arguments);return this};this.emit=function(){var a=this._events;this._events=k._events;k.emit.apply(this,arguments);this._events=a;return this};this._clearEvents=function(a){k.clear(a)};B.isolate(g,e);h.ADFReload=g.ADFReload;h.ADFcall=h.ADFCall=g.ADFCall;d=B.bind(this,i);B.addEvent(h,"unload",d);if(g!=h&&(B.isolate(g,b),B.isOpera||9>B.ieVersion))(!g.Adform||!g.Adform.trackIframe)&&B.isolate(g,n),g.Adform.trackIframe(c.iframe,d)}function n(a){function b(){for(var a=
c.length;a--;)c[a][0].parentNode||(c[a][1](),c.splice(a,1));c.length||(d=clearInterval(d))}var d,c=[];(a.Adform=a.Adform||{}).trackIframe=function(a,e){c.push([a,e]);d||(d=setInterval(b,200))}}function l(a,b){for(var d=a.document.getElementsByTagName("iframe"),c=d.length;0<c--;)try{if(d[c].contentWindow==b)return d[c]}catch(e){}}function i(){var a=this.options.xId,b=this.getUtils();B.removeEvent(h,"unload",arguments.callee);this.emit("destroy");this.destroy&&this.destroy();Q.destroy();p.call(this,
!0);this._clearEvents();this._wallpaper&&(this.toggleWallpaper(),delete this._wallpaper);b&&b.wipeOutBanner&&b.wipeOutBanner(a);this.options=null}function p(b){var d=this.options,c=d.bn,e=d.xId,d=d.seqNo,d=c+(d?"#"+d:""),g=a.adRegister,h=this.win.Adform.adRegister;b?(delete g[d],delete g[c],delete g[e],delete h[d],delete h[c],delete h[e]):g[d]=g[c]=g[e]=h[d]=h[c]=h[e]=this}function w(a){a=a.Adform=a.Adform||{};a.adRegister=a.adRegister||{}}function e(a){function b(d,c){var e=[].slice,g=a.Adform.adRegister;
if(g[d]){var h=[g[d]];if(!/x|#/.test(d))for(var i in g)h[0]!=g[i]&&!i.indexOf(d)&&h.push(g[i]);g=arguments;g=2<g.length?e.call(g,2):!1;for(e=0;e<h.length;e++){i=h[e];var k="string"==typeof c?i[c]:c;"function"==typeof k&&(g?k.apply(i,g):k.call(i))}}}a.ADFReload=function(a){setTimeout(function(){b(a||"1x","reload")},0)};a.ADFcall=a.ADFCall=b}function b(a){var b=a.Adform;b.Events=b.Events||{sendEvent:function(b,d,c,e,g){a.ADFCall(b,"sendEvent",d,c,e,g)}}}function d(a){return(new o.Type[U[a.options.type]](a)).emit("init",
a)}function g(b){var e=b;b||(b=I.shift(),delete b._beforeScript);var h=b.options,i=h.type,k=U[i],j=o.Type[k],u=a.Log,z=h.bn;if(b.$cb)b.$cb();else if({Floating:1,Interstitial:1}[k])if(e&&C(["types/"+k],function v(){if(b._beforeScript)b.$cb=v;else if(!b.$cb){b.$cb=q;g(b)}}),b._beforeScript)k="NextTick",j=null;else return;if(j&&!b._beforeScript){if(u&&(i===E.SLIDER&&(i=E.EXPANDING),u.pushMessage(["BannerType_"+i],"",{bn:z}),i===E.EXPANDING||i===E.SINGLE_EXPANDING))u.pushMessage(["ExpandingBehavior_"+
h.behavior],"",{bn:z}),e=i.charAt(0).toUpperCase()+i.slice(1)+"_",h.showTime&&u.pushMessage([e+"expandTime"],"",{bn:z}),h.hideTime&&u.pushMessage([e+"collapseTime"],"",{bn:z});E.applyHooks(b);b.events.emit("setup",b);b.preventInitialization||d(b)}else if(e)j&&(k="NextTick"),I.push(b),c.write('<script src="'+h.scriptsBase+"rmb/Adform."+k+".js?bv="+a.cache+'"><\/script>');else throw u&&u.pushMessage(["AdConstructor"],"Construct failed",{bn:z}),Error("Construct failed!");}function q(){}function C(b,
d){if(!a.bootLoaded){var e=c.getElementsByTagName("script")[0],g=c.createElement("script");g.type="text/javascript";g.src=(a.shost||("https:"==c.location.protocol?"https://":"http://s1.adform.net"))+"/stoat/boot.js?bv="+a.cache;e.parentNode.insertBefore(g,e);a.bootLoaded=!0}(h._adfq||(h._adfq=[])).push(["require",[b],d])}function F(a,b){if(this._hovered!=a){this._hovered=a;this.interacted=!0;if(a){var d=b.content().assetId;this._eventDelay(this,this.sendEvent,t,d,S)}else this._eventDelay();if(this.onEngage)this.onEngage()}}
var o=a.RMB=a.RMB||{};o.Type=o.Type||{};if(!o.AdConstructor){o.AdConstructor=j;var k=o.EngagementAPI,B=o.lib,Q=o.DOMEvents,E=o.DataParser,R=o.StyleSheet,I=[],t="141",S="Mouse Over on Banner",D={Expanding:[E.EXPANDING,E.TEARBACK],Slider:[E.SLIDER],SingleExpanding:[E.SINGLE_EXPANDING],Floating:[E.FLOATING],Standard:[E.STANDARD],Interstitial:[E.INTERSTITIAL]},U={},W,s,M;for(W in D)if((M=D[W]).push)for(s=M.length;0<s--;)U[M[s]]=W;j.build=function(){a.BWDetect&&a.BWDetect();var b=E.getData(),d=b&&b.options;
d&&(k[d.sendUnload?"load":"version"](d.unloadVersion),b._beforeScript=a._beforeScript,delete a._beforeScript,g(b),d.errorTimeout&&clearTimeout(d.errorTimeout))};j.ibuild=g;j.initialize=d;j.require=C;D=j.prototype;D.BANNER_TYPE="";D.setupUtils=function(a,b){var d=this.getUtils(),c=this.options.xId;"string"==typeof a&&(a=[a]);d&&(d.addBannerAttribute(c,"relativeTargetSWFID",a[0]),d.addBannerAttribute(c,"trackElements",a),b&&d.addBannerAttribute(c,"trackHeatMap",b))};D.setupEngagement=function(a){var b=
this,d=B.singleCall(0);b._eventDelay=B.singleCall(1E3);b._hovered=!1;a.length||(a=[a]);for(var c=0;c<a.length;c++)a[c].on("hover",function(a,c){d(b,F,a,c)})};D.sendEvent=function(b,d,c,e){return a.Events&&a.Events.sendEvent?(a.Events.sendEvent(this.options.xId,b,d,c,e||"",this.BANNER_TYPE),!0):!1};D.getUtils=function(){var b=a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()};D.setupWallpaper=function(){var a=this.options,b=a.wallpaper,d=this.win.document,c=b.cssClass="adform-wallpaper-"+
a.bn,e=b.element||"",e="html"==e?"":!e.indexOf("#")?" "+e:d.documentElement?" body":"";b.target=a.landingPageTarget;R("adform-wallpaper",d).set("."+c+e,"background: "+b.background);("undefined"==typeof b.autoShow||b.autoShow)&&this.toggleWallpaper(!0)};D.toggleWallpaper=function(a){function b(a){a=a||e.event;a=a.target||a.srcElement;return k&&a.id==k?!0:/^(html|body)$/i.test(a.nodeName)}function d(a){i.style.cursor=b(a)?"pointer":""}if(this._wallpaper){var a="string"==typeof a?"true"==""+a:a,c=this.options,
e=this.win;try{var g=e.document,h,i=g.documentElement||g.body;if((h=e.__adform_wallpaper)&&(a||h.cssClass==c.wallpaper.cssClass))B.removeClass(i,h.cssClass),h.link&&(B.removeEvent(g,"mousemove",h._move),B.removeEvent(g,"mouseover",h._cursor),B.removeEvent(g,"click",h._click)),i.style.cursor="",e.__adform_wallpaper=null;if((h=c.wallpaper)&&a){B.addClass(i,h.cssClass);if(h.link){var k=h.element,k=k&&!k.indexOf("#")?k.slice(1):"";B.addEvent(g,"mousemove",h._move=function(a){B.removeEvent(g,"mousemove",
arguments.callee);d(a)});B.addEvent(g,"mouseover",h._cursor=d);B.addEvent(g,"click",h._click=function(a){b(a)&&e.open(h.link,h.target)})}e.__adform_wallpaper=h}}catch(v){}}};D.setupGateway=function(b,d){if(b.get("element")){if(a.Wallpaper&&a.Wallpaper.setup&&!b.get("frompos")){var c=b.get("element"),e=(e=this.getUtils())&&e.banners&&e.banners[this.options.xId];a.Wallpaper.setup({bn:this.options.bn,element:c,utils:e,width:b.get("width"),height:b.get("height"),callback:d})}}else{var g=this;b.onchange("element",
function(){b.off("change:element",arguments.callee);g.setupGateway(b,d)})}};D.adDestroy=i;D.reload=function(){this.adBox&&this.adBox.emit("content:reload")};D.setZIndex=function(a){a=parseInt(a,10);if(!isNaN(a)){var b=this.options,d=U[b.type],c="adBox,collapsed,expanded,wallpaper,container,overlay".split(","),e,g,h,i=c.length;for(this.zIndex=a;i--;)if((g=c[i])&&(e=this[g]))h=a,!("container"==g&&"floating"!=b.behavior)&&!("collapsed"==g&&"SingleExpanding"==d)&&("expanded"==g&&"Expanding"==d&&(h+=1),
"overlay"==g&&(h-=1),e.set("zIndex",h))}}}})(Adform=window.Adform||{},window,document);
(function(a,h){function c(e,b){function d(){g.emit(i)}var g=this;c.super_.call(g);g.created=0;g.options=e;g.data=b;g.container=p.bind(g,g.container);g.show=p.bind(g,g.show);g.hide=p.bind(g,g.hide);g.clear=p.bind(g,g.clear);g.reload=p.bind(g,g.reload);var j=e.loadDelay;if(j)setTimeout(d,1E3*j);else p.onload(h,d);g.on(l,function(){w(e.xId).set(l,!0)});b.social&&(g.setupExtra(g.social=new n.Socialize(e,b.social)),a.Log&&a.Log.pushMessage(["Socialize"],"",{bn:e.bn}));b.adNotice&&"window"!=b.wmode&&g.setupExtra(g.adNotice=
new n.AdNotice(e,b))}a.RMB=a.RMB||{};var j=a.RMB,n=j.Content=a.Content||{};j.AdContent=c;var l="loaded",i="pageLoadComplete";a.PAGE_LOAD_COMPLETE=i;var p=j.lib,w=j.EngagementAPI;p.inherit(c,j.EventEmitter);j=c.prototype;j.container=function(a){var b=this.doc=a.ownerDocument;this.win=b.defaultView||b.parentWindow;this._element=a};j.show=function(){};j.hide=function(){};j.reload=function(){var a=this instanceof n.AdNotice;!(this instanceof n.Socialize)&&!a&&(this.destroy(),this._adbox.get("showing")&&
this.show())};j.destroy=function(){};j.element=function(a,b){var d=this._elem;!1!==b?(d||(d=p.html('<div style="position:relative;width:100%;height:100%;overflow:hidden">',b&&b.ownerDocument)),d&&(b&&b.appendChild(d),"string"==typeof a&&(d.innerHTML=a))):d&&(d.parentNode&&d.parentNode.removeChild(d),d=null);return this._elem=d};j.bind=function(c){if(!this._adbox){var b=this.options,d,g;this._adbox=c;c.once("content:show",function(c){d=setTimeout(function(){for(var d=["img","object","embed","iframe"],
e,g;e=d.pop();){if((e=p.byTag(c,e)[0])&&0<e.offsetWidth&&0<e.offsetHeight)return;e&&(g=e)}a.Log.pushMessage(["AdContent"],"Banner did not render correctly",{bn:b.bn,node:g&&g.nodeName})},3E3)});c.once("content:hide",function(){clearTimeout(d)});c.once("content:destroy",function(){clearTimeout(d)});c.on("change:element",this.container);c.on("content:show",this.show);c.on("content:hide",this.hide);c.on("content:destroy",this.clear);c.on("content:reload",this.reload);(g=c.get("element"))&&this.container(g);
c.get("showing")&&this.show()}};j._clear=j.clear;j.clear=function(){var a=this._adbox;a&&(a.off("change:element",this.container),a.off("content:show",this.show),a.off("content:hide",this.hide),a.off("content:destroy",this.clear),a.off("content:reload",this.reload),this.destroy(),this._clear(),this._adbox=this.doc=this.win=this._element=null)};j.style=function(a){var b=this.element();b&&p.extend(b.style,a);return this};j.setupExtra=function(a){var b=this.bind,d=this.clear;this.bind=function(d){var c=
b.call(this,d);a.bind(d);return c};this.clear=function(){a.clear(this._adbox);return d.call(this)}}})(Adform=window.Adform||{},window,document);
(function(a,h){function c(a,d){c.super_.call(this,a,d.adNotice);var e=this.data;e.width=d.width;e.height=d.height;this.id=n.gid(p+"button-");this.base=a.scriptsBase+"assets/images/OBA/"}a.RMB=a.RMB||{};var j=a.RMB;j.Content.AdNotice=c;var n=j.lib,l=j.DOMEvents,i=j.StyleSheet,p="adform-adnotice-",w={};n.inherit(c,j.AdContent);j=c.prototype;c.supported=function(){return!0};c.READY="ready";j.show=function(){this._element&&!this.created&&this.write()};j.write=function(){var a=this;a.created=(new Date).getTime();
var d=a._element,c=a.doc,e=a.win;e.self||(e=a.win=h);var j=a.statics=i("adbox-static",c);j.adNoticeStyles||(j.adNoticeStyles=!0,j.set(".adform-adnotice","z-index:1;position:absolute!important;top:0!important;right:0!important;left:auto!important;padding:0!important;margin:0!important"));a._elem=n.html('<div class="adform-adnotice" id="'+a.id+'">',c);var p=a.options,o=p.obaId;o?e.$ADP?a.setupAdPlayer(o,d):(j=p.scriptsBase+"adplayer/js/adplayer.min.js",n.loadCSS(c,p.scriptsBase+"adplayer/css/adplayer.min.css"),
n.loadScript(c,j,function(c){c||!e.$ADP?a.setupDefault(d):a.setupAdPlayer(o,d)})):a.setupDefault(d);l.on(a._elem,"hover",function(a){p.disturber.emit("hover",a=="hoverin")})};j.destroy=function(){this.element("",!1);this.created=0};j.getOBAImage=function(a){a=a.toLowerCase().match(/^(bg|cs|da|de-at|de-ch|de|el|es|fi|fr-be|fr-ch|fr|ga|hu|it-ch|it|nl-be|nl|no|pl|ro|sk|sv|uk|en)/);a=(a&&a[0]||"en")+".png";return this.base+a};j.setupAdPlayer=function(a,c){var e=this.win,h=e.$ADP.Registry,i=this.id,j=
this.data,l=this.options;this.element("",c);if(!w[a]){var k=[{title:j.title,text:j.text,url:j.link,linkText:j.linkText,usePopup:!!(e.Adform&&e.Adform.ADFIframe||l.iframeManager||l.iab)}];e.ADFCall(l.xId,function(){this.emit("setupADP",k)});if(k){e=0;for(j=k.length;e<j;++e)h.register(a,k[e])}w[a]=!0}h.createPlayer(a,{domId:i});this.emit("ready")};j.setupDefault=function(a){var c=this.data,g=this.id,h=this.statics,i=105<=c.width&&0.1>1575/(c.width*c.height);h.set(".adform-adnotice a","display:block;width:19px;height:15px;margin:0!important;padding:0!important;position:static!important;background:url("+
this.base+"oba.png) no-repeat;").set(".adform-adnotice img","display:none;border:none;margin:0!important;padding:0!important;position:static!important");i&&h.set("#"+g+" a:hover","width:auto;position:absolute;top:0;right:0;background-position:0 -100px").set("#"+g+" a:hover img","display:block;");this.element('<a href="'+c.link+'" target="_blank">'+(i?'<img src="'+this.getOBAImage(e)+'" alt="">':"")+"</a>",a);this.emit("ready")};var e=navigator.userLanguage||navigator.language||""})(Adform=window.Adform||
{},window,document);
(function(a,h){function c(a,g){c.super_.call(this,a,g);this.id=i.gid(w+"button-");this.on(e,function(){this.sendEvent(145,"Hide Social Bar")}).on(b,function(){this.sendEvent(140,"Facebook Like Button Press")})}function j(){this.emit(b);h.open(this.data.linkBack);return!1}function n(){this.emit(e);this.destroy()}a.RMB=a.RMB||{};var l=a.RMB;l.Content.Socialize=c;var i=l.lib,p=i.addEvent,w="adform-social-",e="collapsed",b="liked";i.inherit(c,l.AdContent);l=c.prototype;c.supported=function(){return!0};
c.READY="ready";c.COLLAPSED=e;c.LIKED=b;l.show=function(){this.destroyed||(this.created&&this.style({display:""}),this._element&&!this.created&&this.write())};l.hide=function(){this.style({display:"none"})};l.write=function(){this.created=(new Date).getTime();var a=this._element,b=this.doc,c=this.data,e=this.id;this._elem=i.html('<div id="'+e+'" class="'+[w+"container",w+"container-"+c.position].join(" ")+'" style="display:none;">',b);this.element('<div class="'+w+'bg"></div><div id="'+e+'-bar" class="'+
w+'bar"></div>',a);a=i.byId(e+"-bar",b);e=this.closeButton=i.html('<div class="'+w+'close">',b);this.close=i.bind(this,n);p(e,"click",this.close);var h=this.linkButton=i.html('<div class="'+w+'link">Like us on Facebook.</div>',b);this.like=i.bind(this,j);p(h,"click",this.like);a.appendChild(h);a.appendChild(e);i.loadCSS(b,c.css);123>c.width&&this.style({width:c.width-("TLV"==c.position?30:2)+"px",overflow:"hidden"});this.emit("ready")};l.destroy=function(){this.closeButton&&i.removeEvent(this.closeButton,
"click",this.close);this.linkButton&&i.removeEvent(this.linkButton,"click",this.like);this.bar=this.linkButton=this.like=this.closeButton=this.close=null;this.element("",!1);this.created=0;this.destroyed=!0};l.sendEvent=function(b,c){if(a.Events&&a.Events.sendEvent){var e=this.options;a.Events.sendEvent(e.xId,b,0,c,"",e.BANNER_TYPE);return!0}return!1}})(Adform=window.Adform||{},window,document);
(function(a,h){function c(b,d){c.super_.call(this,b,d);l.call(this);this.cube3D=this.video=!1;this.created=0;this.keepAlive=b.keepAlive;this.restartAnim=b.restartAnimation;var e=a.Log,g=b.bn;e&&(this.restartAnim&&e.pushMessage(["RestartAnimation"],"",{bn:g}),e.pushMessage(["AssetType_flash"],"",{bn:g}));e=q.gid("Adform");g=this.flashvars=d.flashvars;d=q.extend({},d);g.adId=e;g.expandTime=b.showTime||0;g.collapseTime=b.hideTime||0;g.behavior=b.behavior;g.landingPageTarget=b.landingPageTarget;var h=
[],i;for(i in g)g.hasOwnProperty(i)&&h.push(i+"="+g[i]);var f=b.userParams;if(f)for(i in f)if(f.hasOwnProperty(i)){var k=encodeURIComponent(i);k in g||h.push(k+"="+encodeURIComponent(f[i]+""))}d.flashvars=h.join("&");d.id=this.id="ad"+e;this.data=d;this.assetId=d.assetId||0;this._inScreenLast=0;this.on(M,j)}function j(){var a=C(this.options.xId);if(!this._lastInScreen)a.on("change",q.bind(this,n));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};n.call(this,a)}function n(a){var b=
this,c=+new Date,d=b._inScreenTimer,e=b._lastInScreenChanges;e&&(a=q.extend(e,a));d&&(clearTimeout(d),b._inScreenTimer=0);b._lastInScreen>c-500?(b._lastInScreenChanges=a,b._inScreenTimer=setTimeout(function(){n.call(b,a)},b._lastInScreen+500-c)):(b._lastInScreen=c,b._lastInScreenChanges=null,b.callSwfMethod(x,a))}function l(){var a=!1,b=!1,c=this,d;c.on(E,function(){var e=+new Date;b=!0;a&&((!d||500<e-d)&&c.callSwfMethod(o),d=e)});c.on(o,function(){c.off(o,arguments.callee);a=!0;b&&c.callSwfMethod(o)})}
function i(b,c){function d(a,c,f,e,g){b.emit(a,{x:parseInt(c,10)+i.x,y:parseInt(f,10)+i.y,width:parseInt(e,10),height:parseInt(g,10)})}function e(a){b.emit(a);h.IABcloseAD&&h.IABcloseAD()}for(var g=b.win,i={x:0,y:0},f=b.emit,f=[["initPoliteMode",f,E],["initVideoMode",function(c){b.video=!0;a.Log&&a.Log.pushMessage(["VideoType_"+("undefined"===typeof c||c?"flash":"html")],"",{bn:b.options.bn})}],["initCube3D","cube3D",!0],["initExtender",f,N],["initInScreen",f,M],["startDrag",f,O],["endDrag",d,H],
["updateBox",d,U],["expandComplete",f,W],["collapseComplete",f,s],["close",e,R],["superClose",e,t],["expand",f,I],["rollOutAd",f,S],["videoPlayStartHandler",f,"video:start"],["videoCompleteHandler",f,"video:end"]],k=f.length;0<k--;)(function(a,d,f){function e(){var a=J.call(arguments);"undefined"!==typeof f&&a.unshift(f);d.apply(b,a)}function g(){b[d]=f}c[a]="function"==typeof d?e:g}).apply(b,f[k]);c.initScroll=function(){var a=b.options.iab?g.parent:g;q.addEvent(a,"scroll",function(){q.removeEvent(a,
"scroll",arguments.callee);b.callSwfMethod("scroll")})};c.initSingleExpanding=function(a,c){b.emit("expandSettings",i={x:-parseInt(a,10),y:-parseInt(c,10)})};c.toggleFullScreen=function(a){b.emit(D,"true"==""+a)}}function p(a){var b=a.id,c,d,e="Handlers"+a.options.xId;d=a.win;q.isolate(d,w);c=d.Adform.swfCallbacks;d=d.Adform.VideoInterstitialHandlers;d=d[e]=c[b]=c[b]||{};i(a,d)}function w(a){function b(a,d){if(a&&(a=c["ad"+a])&&a[d])a[d]()}var c="swfCallbacks",d="VideoInterstitialHandlers",e=a.Adform=
a.Adform||{};if(!e[c]||!e[d])c=e[c]=e[c]||{},d=e[d]=e[d]||{},a.ADFClose=function(a){b(a,"close")},a.ADFSuperClose=function(a){b(a,"superClose")},a.ADFExpand=function(a){b(a,"expand")}}function e(a){var b=['classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"','codebase="'+location.protocol+"//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version="+a.version+',0,0,0"'],c=[],d=['type="'+F+'"','pluginspage="'+location.protocol+'//www.macromedia.com/go/getflashplayer"'],e;for(e in a)a.hasOwnProperty(e)&&
!~"object|undefined".indexOf(typeof a[e])&&("id"==e||"width"==e||"height"==e?b.push(e+'="'+a[e]+'"'):"src"==e?c.push('<param name="movie" value="'+a[e]+'" />'):c.push('<param name="'+e+'" value="'+a[e]+'" />'),"id"==e?d.push('name="'+a[e]+'"'):d.push(e+'="'+a[e]+'"'));return"<object "+b.join(" ")+">"+c.join("")+"<embed "+d.join(" ")+" /></object>"}function b(a,b){var c=q.byId(a,b);c&&"OBJECT"==c.nodeName&&("msie"==q.browser()?(c.style.display="none",function(){if(4==c.readyState){var d=q.byId(a,b);
if(d){try{for(var e in d)if("function"==typeof d[e])try{d[e]=null}catch(g){}}catch(f){}d.parentNode.removeChild(d)}}else setTimeout(arguments.callee,10)}()):c.parentNode.removeChild(c))}function d(a,b){var c=q.byId(a,b);return c&&q.byTag(c,"embed")[0]}a.RMB=a.RMB||{};var g=a.RMB;g.Content.FlashTag=c;var q=g.lib,C=g.EngagementAPI,F="application/x-shockwave-flash",o="pageLoadComplete",k="loaded",B="percentLoaded",Q="canceled",E="politeReady",R="hide",I="show",t="close",S="rollOut",D="fullScreen",U=
"updateBox",W="expandComplete",s="collapseComplete",M="initInScreen",x="updateInScreen",N="extender",O="startDrag",H="endDrag";q.inherit(c,g.AdContent);g=c.prototype;c.supported=function(a){return X>=(a||1)};c.observe=function(a){var b=c._timer,d=c._toObserve=c._toObserve||[];d.push(a);b||(b=setInterval(function(){for(var a=d.length;a--;)d[a]()&&d.splice(a,1);d.length||(clearInterval(b),delete c._timer)},500),c._timer=b)};c.READY="ready";c.PERCENT=B;c.LOADED=k;c.CANCELED=Q;c.POLITE_READY=E;c.HIDE=
R;c.CLOSE=t;c.SHOW=I;c.ROLL_OUT=S;c.EXPAND_SETTINGS="expandSettings";c.EXPAND_UPDATE=U;c.EXPAND_END=W;c.COLLAPSE_END=s;c.FULL_SCREEN=D;c.LOAD_COMPLETE=o;c.INSCREEN_INIT=M;c.INSCREEN_UPDATE=x;c.EXTENDER=N;c.START_DRAG=O;c.END_DRAG=H;c.setCallbacks=i;c.setupPolite=l;g.write=function(){var a=this,b=a._element,d=e(a.data);p(a);a.element(d,b);a.created=new Date;a.emit("ready");setTimeout(function(){function b(){var c=q.byId(a.id,a.doc),d=c&&q.byTag(c,"embed")[0];try{return c.PercentLoaded(),c}catch(e){try{return d.PercentLoaded(),
d}catch(f){}}}function d(){try{var b=e.PercentLoaded();a.emit(B,b);100==b&&(a.emit(k),f=clearInterval(f))}catch(c){a.emit(Q),f=clearInterval(f)}}var e,f;(e=b())?f||(f=setInterval(d,100)):c.observe(function(){var c;if(!(c=!a.created))if(c=e=b())f||(f=setInterval(d,100)),c=!0;return c})},100)};g.destroy=function(){this.video&&this.callSwfMethod("pauseVideo");var a=this.id,c=this.win;(c=c&&c.Adform||h.Adform)&&c.swfCallbacks&&c.swfCallbacks[a]&&delete c.swfCallbacks[a];b(this.id,this.doc);this.element("");
this.created=0};g.callSwfMethod=function(a){function b(){if(!k[a]&&(!j||!j[a]))0<s--?setTimeout(b,100):c.emit("failed:"+a,l);else{try{"undefined"!=typeof k[a]?d.Adform_swfCallFix?d.Adform_swfCallFix(g,a,l):k[a].apply(k,l):"undefined"!=typeof j[a]&&j[a].apply(j,l)}catch(e){}c.emit("called:"+a,l)}}var c=this;if(c.created){var d=c.win,e=c.doc,g=c.id,f=c._elem;if(d!=h&&!e.addEventListener){var i=e.createElement("script");i.text="function Adform_swfCallFix(a,b,c){a=document.getElementById(a);return a[b].apply(a,c);}";
f.parentNode.insertBefore(i,f)}var k=q.byId(g,e),j=q.byTag(k,"embed")[0],l=J.call(arguments,1),s=20;c.emit("call:"+a,l);200>new Date-c.created?setTimeout(b,"safari"==q.browser()?100:0):b()}};g.show=function(){this._element&&!this.created&&(this.write(),this.forceRender())};g.hide=function(){if(this._element&&this.created){var a=d(this.id,this.doc);a&&a.blur&&a.blur();this.video&&!this.restartAnim?(this.callSwfMethod("pauseVideo"),this.cube3D&&this.callSwfMethod("resetCube3D"),this.forceRender()):
this.keepAlive?this.forceRender():this.destroy()}};g.forceRender=function(){if(!h.opera){var a=d(this.id,this.doc);if(a){var b=this.data.width;setTimeout(function(){a.width=b+1},0);setTimeout(function(){a.width=b},0)}}};var J=Array.prototype.slice,X=function(){var a=navigator.plugins,b=navigator.mimeTypes,c=h.ActiveXObject,d=16,e,a=a&&a["Shockwave Flash"]&&(!b||!b["application/x-shockwave-flash"]||b["application/x-shockwave-flash"].enabledPlugin)&&a["Shockwave Flash"].description||"";if(!a&&c)for(;6<=
d--;)try{e=new c("ShockwaveFlash.ShockwaveFlash."+d);6==d&&(e.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=e.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(f){}return parseFloat(a.replace(/^.*?(\d+[\.,].*$)/,"$1"))||0}()})(Adform=window.Adform||{},window,document);
(function(a,h,c){function j(b,c){j.super_.call(this,b,c);this.assetId=c.assetId||0;this.xId=b.xId;this.restartAnim=b.restartAnimation;var d=a.Log,g=b.bn;d&&(d.pushMessage(["VideoType_html"],"",{bn:g}),d.pushMessage(["AssetType_video"],"",{bn:g}),this.restartAnim&&a.Log.pushMessage(["RestartAnimation"],"",{bn:g}));d=e.gid("Adform");c.id=this.id="ad"+d}function n(a){function b(){var a=q.currentTime,d=q.duration,e=+new Date,g=e-v,h=a-B;v=e;B=a;if(d){e=!1;if(h&&(h=g/(1E3*h)))e=2<Math.round(Math.abs(q.playbackRate/
h));a/=d;p!=a?(p=a,n=5,i.emit("timeupdate",p,e)):"playing"==o&&!--n&&0.9<p&&(c({type:"ended"}),n=5)}}function c(b){if("ended"==b.type&&a.loop)h(0),q.play();else if("ended"==b.type&&(h(0),q.pause()),b=q.paused||"ended"==b.type?!p||1===p?"stoped":"paused":"playing",b!=o)i.playbackState=o=b,i.emit("state",b)}function g(a){var b=a.total||q.duration;if(0<b)try{var c=(a.loaded||q.buffered&&q.buffered.end(0)||0)/b;c>t&&(t=c,i.emit("loadProgress",t))}catch(d){}}function h(a){try{q.currentTime=a*q.duration}catch(b){}}
var i=this,k=a.document;"undefined"==typeof S&&(S=k.createElement("video"));var j=w(a.sources);i.source=j;var q=e.html("<video "+l(a)+' preload="none" style="float:left"><source src="'+j.src+'"></video>',k);q.loop=!1;i.element=q;var o,n,p=-1,t=-1,v=0,B=0;d(q,"timeupdate",b);setInterval(function(){b()},500);k="play,pause,playing,seeking,seeked,stalled,ended,timeupdate".split(",");for(j=0;j<k.length;j++)d(q,k[j],c);c({});if(q.buffered)var C=setInterval(function(){g({});1<=t&&clearInterval(C)},500);
else d(q,"progress",g);i.setProgress=h;a.autoplay&&setTimeout(function(){q.play()},0)}function l(a){for(var b=[],c=0,d,e;c<D.length;c++)d=D[c],(e=a[d])&&(!0===e?b.push(d):b.push(d+'="'+e+'"'));return b.join(" ")}function i(a){function c(a){a=(e.getMousePos(a).pageX-o.pageX+o.relativeX)/n.offsetWidth;h(a)}function h(a){a=0>a?0:1<a?1:a;j(a);l.emit("seek",a)}function i(){g(q,"mousemove",c);g(q,"mouseup",i);g(q,"mouseout",k);l.emit("endSeek")}function k(a){for(a=a.relatedTarget;a&&a!=l;)a=a.parentNode;
a!=l&&i()}function j(a){y.style.width=100*a+"%"}var l=this;b.call(l);var q=a.container,o=null,p=e.html('<div class="'+C+'seek"><div class="'+C+'seek-border"><div class="'+C+'seek-background"><div class="'+C+'seek-loaded"></div><div class="'+C+'seek-played"></div></div></div></div>',q.ownerDocument),n=p.firstChild.firstChild,t=n.firstChild,y=t.nextSibling;y.style.width=0;l.element=p;d(p,"mousedown",function(a){l.emit("startSeek");a.preventDefault?a.preventDefault():a.returnValue=!1;o=e.getMousePos(a);
h(o.relativeX/p.offsetWidth);d(q,"mousemove",c);d(q,"mouseup",i);d(q,"mouseout",k)});l.setProgress=j;l.setLoadProgress=function(a){t.style.width=100*a+"%"}}function p(a){var c=this;b.call(c);var g=a.className,a=c.element=e.html('<div class="'+g+'"></div>',a.document);d(a,"click",function(a){a.preventDefault?a.preventDefault():a.returnValue=!1;c.emit("buttonClick",g)})}function w(a){if(a&&a.length)for(var b=S,c=0;c<a.length;c++){var d=a[c];if(d){var e=d.file;if(e){var g=!1;if(d.mime&&d.codecs)d=d.mime+
'; codecs="'+d.codecs+'"';else{g=e.match(/\.(mp4|webm|mkv|ogv|ogg|avi)/i);if(!g)continue;g=g[1].toLowerCase();d={mp4:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',avi:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',mkv:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',webm:'video/webm; codecs="vp8, vorbis"',ogv:'video/ogg; codecs="theora, vorbis"',ogg:'video/ogg; codecs="theora, vorbis"'}[g]}if(d){var h;try{var i;if(!(i=b.canPlayType(d))){var k;if(k=g)k=E&&("mp4"==g||"m4v"==g)||Q&&"m3u8"==g?"maybe":void 0;
i=k}h=i}catch(j){}if("probably"==h||"maybe"==h)return{src:e,type:d}}}}}}a.RMB=a.RMB||{};h=a.RMB;h.Content.VideoTag=j;var e=h.lib,b=h.EventEmitter,d=e.addEvent,g=e.removeEvent;e.inherit(j,h.AdContent);var h=j.prototype,q={progr0:{id:"25",name:"Video Play Start"},progr25:{id:"26",name:"Played 25% Of Video"},progr50:{id:"27",name:"Played 50% Of Video"},progr75:{id:"28",name:"Played 75% Of Video"},progr100:{id:"29",name:"Video Playback Complete"},play:{id:"30",name:"Play Button Press"},pause:{id:"31",
name:"Pause Button Press"},stop:{id:"32",name:"Stop Button Press"},soundOn:{id:"33",name:"Sound ON Button Press"},soundOff:{id:"34",name:"Sound OFF Button Press"},close:{id:"23",name:"Close Button Press"}},C="adform-video-",F=C+"state-",o=C+"sound-",k=e.isIPad,B=e.isIPhone,Q=B||k,E=e.isAndroid,R=e.isWinPhone,I=B||R,t,S;j.supported=function(a){"undefined"==typeof t&&(S=c.createElement("video"),t=!!S.canPlayType);return!t?!1:!w(a)?!1:!0};j.READY="ready";j.LOADED="loaded";j.HIDE="hide";h.write=function(){function a(){y.play()}
function b(a){var d=y.muted;c(!d);c(d);za=a;z.className=z.className.replace(Ab," "+F+a)}function c(a){Q||(y.muted=a,z.className=z.className.replace(r," "+o+(a?"off":"on")))}function h(a,b){if(na.length||fa){if(!b&&a!=sa){var c=100*sa,d=100*(0.5<sa-a?1.1:a);0>=c&&0<d?(fa=fa||l.list(Z).length,l.emit(Z)):100>=c&&100<d&&(fa=fa||l.list(ca).length,l.emit(ca));for(var e=0,f=na.length;e<f;e++)if(na[e]>=c&&na[e]<d){l.sendEvent(q["progr"+na[e]]);na.splice(e,1);break}}sa=a}}var l=this,t=l.data,w=l.options,H=
l._element,J=t.document=l.doc,D=new n(t);e.loadCSS(J,t.css);var u=t.closeButtonAlign;l.element('<div class="'+C+"container "+C+"device-"+(B?"iphone":k?"ipad":E?"android":"default")+'"></div>',H);var H=l._elem,z=H.firstChild,y=D.element;z.appendChild(y);var v,A=["width:"+t.width+"px","height:"+t.height+"px"];t.poster&&(A.push("background-image:url('"+t.poster+"')"),A.push("background-size:contain"));var L=e.html('<a class="adform-video-poster" style="'+A.join(";")+'"></a>');z.appendChild(L);var f,
m,G,R;if(I){L.style.position="relative";y.style.position="absolute";y.style.top="-100000px";var A=0.25*Math.min(t.width,t.height)/90,A="scale("+A+", "+A+");",S=e.html('<div style="'+["-ms-transform:"+A,"-webkit-transform:"+A,"-o-transform:"+A,"-moz-transform:"+A].join("")+'" class="adform-video-big-play"></div>');L.appendChild(S);d(L,"click",a);t.link&&t.poster&&(v=function(){g(L,"click",a);L.removeChild(S);L.href=t.link;L.target=w.landingPageTarget})}else f=C+"play-pause",m=C+"stop",G=C+"sound",
f=new p({className:f,document:J}),m=new p({className:m,document:J}),G=new p({className:G,document:J}),R=new i({container:z}),t.link?(L.href=t.link,L.target=w.landingPageTarget):L.style.cursor="auto",v=function(){L.style.opacity=0},z.appendChild(f.element),z.appendChild(m.element),z.appendChild(G.element),z.appendChild(R.element);if(v)D.on("state",function(a){if(a=="playing"){D.off("state",arguments.callee);v()}});u&&(A=new p({className:C+"close",document:J}),A.element.appendChild(e.html('<div><div class="adform-video-close-icon">&times;</div></div>',
J)),z.className+=" "+C+"stopAlign-"+u,z.appendChild(A.element),A.on("buttonClick",function(){y.pause();l.emit(j.HIDE);l.sendEvent(q.close)}));var za=D.playbackState,Aa=!1,Ab=RegExp("\\s*"+F+"\\S+|$"),r=RegExp("\\s*"+o+"\\S+|$");c(l.data.muted);b("stoped");D.on("state",function(a){Aa||b(a)});var sa=0,na=[0,25,50,75,100],fa=!1,Z="video:start",ca="video:end";I?(D.on("timeupdate",h),d(y,"ended",function(){sa=0.9;h(0)}),E&&d(y,"click",function(){y.play()})):(d(y,"volumechange",function(){c(y.muted)}),
D.on("timeupdate",function(a){if(!Aa){h(a);R.setProgress(a)}}),D.on("loadProgress",R.setLoadProgress),f.on("buttonClick",function(){if(za=="playing"){y.pause();l.sendEvent(q.pause)}else{y.play();l.sendEvent(q.play)}}),m.on("buttonClick",function(){za=="playing"&&y.pause();D.setProgress(0);l.sendEvent(q.stop)}),R.on("seek",function(a){D.setProgress(a);h(a,true)}),R.on("startSeek",function(){Aa=true;y.pause()}),R.on("endSeek",function(){Aa=false;za=="playing"&&y.play()}),G.on("buttonClick",function(){c(!y.muted);
y.muted?l.sendEvent(q.soundOff):l.sendEvent(q.soundOn)}));l.pause=function(){y.pause()};l.play=function(){if(!y.src){y.src=D.source.src;y.load()}y.play()};H.appendChild(z);l.created=!0;l.emit("ready");l.emit("loaded")};h.show=function(){this._element&&!this.created&&this.write()};h.hide=function(){this.created&&(this.restartAnim?this.destroy():this.pause())};h.destroy=function(){this.pause();this.element("",!1);this.created=0};h.sendEvent=function(b){b&&a.Events&&a.Events.sendEvent&&a.Events.sendEvent(this.xId,
b.id,this.assetId,b.name,"")};e.inherit(n,b);var D="id,class,width,height,controls,autoplay,poster".split(",");e.inherit(i,b);e.inherit(p,b)})(Adform=window.Adform||{},window,document);
(function(a){function h(c,i){h.super_.call(this,c,i);this.created=!1;this.data=i;this.adId=j.gid("Adform");this.data.id=this.id="ad"+this.adId;this.assetId=i.assetId||0;a.Log&&a.Log.pushMessage(["AssetType_image"],"",{bn:c.bn})}a.RMB=a.RMB||{};var c=a.RMB;c.Content.ImageTag=h;var j=c.lib,n=j.addEvent;j.inherit(h,c.AdContent);c=h.prototype;h.supported=function(){return!0};h.READY="ready";h.LOADED="loaded";h.HIDE="hide";c.show=function(){this._element&&!this.created&&this.write()};c.hide=function(){};
c.write=function(){var a=this,c=a.data,h=a._element,w=a.options,e=c.useClose,b='<img src="'+c.src+'" border="0" id="'+c.id+'" width="'+c.width+'" height="'+c.height+'" alt="" style="cursor:pointer" />';c.link&&(b='<a href="'+c.link+'" target="'+w.landingPageTarget+'">'+b+"</a>");e&&(b+='<img src="'+w.scriptsBase+'assets/images/close-sprite.png" style="width:50px!important;height:50px!important;position:absolute!important;top:0!important;right:0!important;padding:0!important;margin:0!important;cursor:pointer;">');
a.element(b,h);c=j.byTag(a._elem,"img");n(c[0],"load",function(){a.emit("loaded")});e&&n(c[1],"click",function(){a.emit("hide",!0)});a.created=!0;a.emit("ready")};c.destroy=function(){if(this._elem){var a=j.byTag(this._elem,"img")[0];a.src=a.src}this.element("",!1);this.created=!1}})(Adform=window.Adform||{},window,document);
(function(a){function h(b,c){var g=this;h.super_.call(g,b,c);g.id="ad"+i.gid("Adform");w.setupPolite.call(g);g.video=!1;w.setCallbacks(g,g.external={});g.external.resize=function(a,b){c.height=a;c.width=b;var e=g.element();if(e&&(e=i.byTag(e,"iframe")[0]))e.height=e.width="100%";g._adbox&&g._adbox.set({width:a,height:b})};g.external.setLayout=function(a){g.external.resize(a.width,a.height);var b=a.type&&i.isMobile&&(i.isIOS||i.isAndroid);g._adbox&&b&&g._adbox.reset(a)};g.sharedEvents=new p;var j=
g.flashvars=c.flashvars,c=i.extend({},c);j.expandTime=b.showTime||0;j.collapseTime=b.hideTime||0;j.behavior=b.behavior;var n=b.landingPageTarget;j.landingPageTarget="_self"==n?"_parent":n;if(n=b.userParams)for(var F in n)n.hasOwnProperty(F)&&!(F in j)&&(j[F]=n[F]);c.id=g.id;g.data=c;g.assetId=c.assetId||0;g.state(e);g.once(a.PAGE_LOAD_COMPLETE,g.write);a.Log&&a.Log.pushMessage(["AssetType_html"],"",{bn:b.bn});var o;g.on(w.INSCREEN_INIT,function(){var a=l(b.xId),c=w.INSCREEN_UPDATE;o||(o=!0,a.on("change",
function(a){g.callSwfMethod(c,a)}));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};g.callSwfMethod(c,a)})}function c(a,c,e,h){var l=a.domain,n=i.isIE&&11>i.ieVersion&&l!=a.location.hostname,o=n?"frameElement":"this",a=a.createElement("div"),k="<!DOCTYPE html><title>ad</title><base href='"+e.src.replace(/[^\/]+$/,"")+"'>",p="eval("+o+".getAttribute('data-onload'))",h="<script>parent."+h+"&&parent."+h+"(window)<\/script><script src='"+e.src+"'><\/script>";a.innerHTML='<iframe width="'+
e.width+'" height="'+e.height+'" src="javascript:\'\'"'+(n?"":' onload="'+p+'"')+' allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>';a=a.firstChild;a.setAttribute("data-contents",(n?"":k)+h);a.setAttribute("data-onload","("+j+")("+o+","+n+")");c.appendChild(a);n&&(a.src="javascript:void(document.write('"+(k+"<script>document.domain='"+l+"';"+p+"<\/script>").replace(/'/g,
"\\'").replace(/\//g,"\\/")+"'));")}function j(a,c){function e(){j.open();j.write(h);i.__rendered__=!0}var h=a.getAttribute("data-contents"),i=a.contentWindow,j=i.document;i.__rendered__||(i.__rendered__=!0,c?e():setTimeout(e,0))}a.RMB=a.RMB||{};var n=a.RMB;n.Content.HTML=h;var l=n.EngagementAPI,i=n.lib,p=n.EventEmitter,w=n.Content.FlashTag,e="initial";i.inherit(h,n.AdContent);h.READY="ready";h.supported=function(){return!i.isIOS&&!i.isAfmaSDK&&(i.isAndroid||i.isMobile&&!i.isIE)?i.isSafari||i.isChrome||
i.isOperaMobile||i.isFF||i.isInternet||i.isAndroidApp||i.isOperaWebKit:!0};n=h.prototype;n.show=function(){var a=this._element;this.write();setTimeout(function(){a&&(a.style.background="")},100);this.element().style.width=this._width;this.state("visible")};n.hide=function(){var a=this._element;this.state("hidden");a&&this.created&&(this.callSwfMethod("pauseVideo"),a=this.element().style,this._width=a.width,a.width=0)};n.write=function(){var b=this,d=b._element;if(d&&!b.created){var e=b.options,h=
b.data,j=b.doc,l=b.win,n=i.gid("AdformWin");l[n]=function(c){function d(){h.close()}b._contentWindow=c;var h=c.document,j=b.flashvars;c._Adform=a;c._AdformContent=b;var l=b.options.scriptsBase;c.API_URL=l+"rmb/Adform.DHTML.js?bv="+j.bv;var n='<script src="'+l+"rmb/Adform.WriteHelper.js?bv="+j.bv+'"><\/script>',q=[],o,p=function(a){h._write(a+"<script>document._finish();<\/script>")};h._write=h.write;h.write=i.isIE?function(a){var a=a+"",b;q.length?q.splice(-1,0,a):(b=a.match(/(<\!--[\s\S]*?--\>)|(<script(?:\s+[^>]*)?>[\s\S]*?<\/script>)/i))?
(a=b[2],b=RegExp.leftContext+b[0],q.unshift(RegExp.rightContext),a?h._write(b+(a.match(/^<script[^>]+?src/i)?n:"<script>document._continue();<\/script>")):(h._write(b),h._continue())):p(a)}:p;h._continue=function(){var a=q.join("");q.length=0;h.write(a)};h._writeln=h.writeln;h.writeln=function(a){h.write(a+"\r\n")};h._finish=function(){clearTimeout(o);o=setTimeout(d,10)};var w;i.addEvent(c,"load",function(){if(!w){w=!0;i.removeEvent(c,"load",arguments.callee);var d=a.ADFEventsInstance;if(d&&d.addElement){var j=
h.documentElement.id=i.gid("adform-dhtml-");d.addElement(e.xId,[j],c)}b.emit("loaded")}})};d=b.element(" ",d);c(j,this._container||d,h,n);h=d.style;b._width=h.width;h.width=0;b.created=(new Date).getTime();b.emit("ready")}};n.destroy=function(){if(this._elem&&this.created){this.state("destroyed");var b=i.byTag(this._elem,"iframe")[0],c=b.contentWindow||this._contentWindow,e=a.ADFEventsInstance;e&&e.removeElement&&c.document&&e.removeElement(this.options.xId,[c.document.documentElement.id],c);this.docCloseTimer=
clearTimeout(this.docCloseTimer);c.cleanupAdform&&c.cleanupAdform();c._AdformContent=c._Adform=null;this.sharedEvents.clear();i.isIE&&(b.src="about:blank");this.element("",!1);this.created=0}};n.callSwfMethod=function(a){var c=this.sharedEvents;c.emit.apply(c,arguments);this.emit("call:"+a)};n.state=function(a){var c=this._state,e;a&&a!=c&&(this._state=a,(e=this.sharedEvents).emit("changed:state",a),"visible"==a?e.emit("show"):"visible"==c&&e.emit("hide"));return this._state}})(Adform=window.Adform||
{},window,document);
(function(a,h,c){function j(a){var g=this;j.super_.call(g,a);var n,C=!1,F=a.flash,o=a.video,k=a.image,B=a.polite,Q=a.html,a=a.options;if(F&&l.supported(F.version))n=new l(a,F),C=!0;else if(Q&&w.supported())n=new w(a,Q);else if(o&&i.supported(o.sources))n=new i(a,o);else if(k&&p.supported())n=new p(a,k),C=!F;else return;var E=g.adBox=(new e).publish("adBox",g);a.hidden&&g.hide();B&&p.supported()?(B=new p(a,B),B.style({position:"absolute",top:0,left:0,zIndex:1}),E.content(B,!0),B.on(b,function(){B.off(b,
arguments.callee);E.content(n);if(n instanceof l)n.on(l.LOADED,function(){B.clear()});else B.clear()})):E.content(n,!0);g.onEngage=function(){g.onEngage=null;E.content().emit(b)};g.setupEngagement(E);F=n.data;a.iab&&(o=h.frameElement.style,o.width=F.width+"px",o.height=F.height+"px");o=a.iframeAPI;o.hasAPI&&o.register(F);F={position:a.position};a.$tag&&(F.before=a.$tag);E.draw(c,F);g.setupUtils(E.id,C?E.id:null);g.setupGateway(E)}a.RMB=a.RMB||{};var n=a.RMB;n.Type.Standard=j;var l=n.Content.FlashTag,
i=n.Content.VideoTag,p=n.Content.ImageTag,w=n.Content.HTML,e=n.AdBox,b=a.PAGE_LOAD_COMPLETE;n.lib.inherit(j,n.AdConstructor);a=j.prototype;a.BANNER_TYPE="Standard Banner";a.destroy=function(){this.adBox&&this.adBox.destroy();this.adBox=null};a.show=function(){this._hidden&&(this._hidden=!1,this.adBox.set("visible",!0))};a.hide=function(){this._hidden||(this._hidden=!0,this.adBox.set("visible",!1),this.reload())}})(Adform=window.Adform||{},window,document);Adform.RMB.AdConstructor.build();