(function(l){function v(a,b,c){c||(c=b,b=[]);a in k&&k[a]&&(k[a]=!1,p--);m(b,function(){h[a]=c.apply(null,arguments);delete k[a];r()});p||(q=!1,r())}function m(a,b){for(var c=0,d=a.length,e,f=[];c<d;c++)if(e=a[c],e in h)f[c]=h[e];else{n.push(arguments);q||(q=setTimeout(w,0));return}b.apply(null,f)}function r(){var a=n,b=0,c=a.length;for(n=[];b<c;b++)m.apply(null,a[b])}function w(){for(var a=n,b=0,c=a.length,d=[],e,f;b<c;b++)for(e=a[b][0],f=e.length;f--;)e[f]in h||e[f]in k||(d.push(e[f]),k[e[f]]=!0,
p++);d.length&&(a=s.createElement("script"),a.async=a.defer=!0,a.src=x+"//s1.adform.net/stoat/load/v/0.0.13/e/"+h.$env.$hash()+"/i/"+h.$ignore+"/r:"+d.sort().join(":"),d=s.getElementsByTagName("script")[0],d.parentNode.insertBefore(a,d))}function t(){for(var a=arguments,b=0,c=a.length,d=[];b<c;b++)y(a[b])||d.push(a[b]);return d.length?u.apply(g,d):g.length}function y(a){function b(b){b.apply(null,a.slice(1))}var c=a[0],d=h[c];d?b(d):m([c],b)}var g=l["_adfq"]||(l["_adfq"]=[]),s=l.document,x="https:"===
l.location.protocol?"https:":"http:",h={require:m,$boot:{window:l}},n=[],k={},p=0,u,q;(function(){var a;u=g.push;g.define=v;g.push=t;a=g.slice();g.length=0;t.apply(g,a)})()})(window);
_adfq.define("$env",["$boot"],function(P){function w(){function m(b,x){var a=x.charAt(0).toUpperCase()+x.slice(1);return f(b,x,"ms"+a,"moz"+a,"webkit"+a)}function f(b){for(var a=arguments,c=a.length;--c;)if(a[c]in b)return a[c]}function d(a,b){return 0<=(""+a).toLowerCase().indexOf(b.toLowerCase())}var b=P.window,c=b.document,e=c.documentElement,n=b.navigator,g=b.parent,h=n.vendor,a=n.userAgent,q=b.Adform||{},r=c.createElement("div"),s=function(a){for(var b=[!0],c=a.top,d;a!=c;){try{d=!!(a=a.parent).Image}catch(e){d=
!1}b.push(d)}return b}(b),g=b!=g,l=!g||s[1],y=!g||s[s.length-1],p=function(){var a=n.plugins,c=n.mimeTypes,a=a&&a["Shockwave Flash"]&&(c&&c["application/x-shockwave-flash"]&&c["application/x-shockwave-flash"].enabledPlugin||a["Shockwave Flash"]).description||"",c=!a&&b.ActiveXObject,d=16,e;if(c)for(;5<=d--&&!a;)try{e=new c("ShockwaveFlash.ShockwaveFlash."+d);6===d&&(e.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=e.GetVariable("$version").replace(/,/i,".")}catch(f){}}catch(g){}return parseFloat(a.replace(/^.*?(\d+[.,].*)/,
"$1"))||0}(),E=10.3<=p&&!y,F=m(c,"hidden"),G=!!F,t=/MSIE|Trident/i.test(a),w=t&&("Microsoft Internet Explorer"===n.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))?parseFloat(RegExp.$1):-1,r=f(r,"addEventListener"),u=d(h,"apple computer"),z=d(a,"ipad"),A=d(a,"iphone"),v=z||A,k;k=v&&(k=/\sos\s(\d+)_\d+/i.exec(a))&&(k=4<k[1]>>0);var B=d(h,"google"),H=!v&&d(a,"android"),I="ontouchstart"in c||"ontouchstart"in b,J=(u||B)&&/(chrome|crios)+\/[\d\.]+\s/i.test(a),K=/Firefox\/[\d\.]+/i.test(a),
C=d(a,"opera"),h=C&&d(a,"opr")&&d(h,"opera software"),D=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&u,a=t&&(d(a,"IEMobile")||d(a,"WPDesktop")),L=D&&!("webkitRequestAnimationFrame"in b),M="screenX"in b,N="outerWidth"in b,O="mozInnerScreenX"in b,e=e.msContentZoomFactor,c=c.fireEvent&&c.attachEvent,Q=m(b,"requestAnimationFrame"),q=q.ADFIframe;return{result:[g,l,y,E,G,t,r,u,z,A,v,k,B,H,I,J,K,C,h,D,a,L,M,N,O,e,c,q],exports:{nop:function(){},access:s,frame:g,accParent:l,accTop:y,flashVersion:p,
flInScreen:E,hidden:F,hasHidden:G,isIE:t,ieVersion:w,addEvent:r,isApple:u,isIPad:z,isIPhone:A,isIOS:v,isIOSF:k,isGoogle:B,isAndroid:H,isTouch:I,isChrome:J,isFirefox:K,isOpera:C,isOperaWebkit:h,isSafari:D,isIEMobile:a,isSafari5OrLess:L,screenX:M,outerWidth:N,mozInnerScreenX:O,msZF:e,ieDomEvents:c,reqAni:Q,adfFrm:q}}}var p={$hash:function(){if(!l){for(var m=[],f=w(),d=f.result,f=f.exports,b=0,c=d.length,e=0,c=c+(6-c%6)%6;b<c;b++)e=e<<1|!!d[b],5==b%6&&(m.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(e)),
e=0);for(b in f)p[b]=f[b];l=m.join("")}return l}},l;return p});
_adfq.define("$ignore",function(){return"wAA";});